use bevy::prelude::*;

/// Test config type generated by the `GameConfig` derive macro.
#[derive(Resource, Debug, Clone, PartialEq, Default, crate::GameConfig)]
#[game_config(defaults = "TestDefaults", path = "config/test.ron", ext = "test.ron")]
pub(super) struct TestConfig {
    pub(super) value: f32,
}
