use bevy::prelude::*;

use crate::{handle::DefaultsHandle, systems::*};

/// Test config type generated by the `GameConfig` derive macro.
#[derive(Resource, Debug, Clone, PartialEq, Default, crate::GameConfig)]
#[game_config(defaults = "TestDefaults", path = "config/test.ron", ext = "test.ron")]
struct TestConfig {
    value: f32,
}

// ── seed_config tests ────────────────────────────────────────────

#[cfg(feature = "progress")]
mod seed_config_tests {
    use super::*;

    fn test_app() -> App {
        let mut app = App::new();
        app.add_plugins((MinimalPlugins, AssetPlugin::default()))
            .init_asset::<TestDefaults>()
            .add_systems(Update, seed_config::<TestDefaults>.map(drop));
        app
    }

    /// Without a `DefaultsHandle` resource, `seed_config` reports zero
    /// progress and does not insert the `Config` resource.
    #[test]
    fn returns_zero_progress_without_handle() {
        let mut app = test_app();
        app.update();
        assert!(
            app.world().get_resource::<TestConfig>().is_none(),
            "TestConfig should not exist when no DefaultsHandle is present"
        );
    }

    /// When `DefaultsHandle` exists but the asset is not yet loaded,
    /// `seed_config` reports zero progress.
    #[test]
    fn returns_zero_progress_when_asset_not_loaded() {
        let mut app = test_app();

        // Insert a handle pointing to a non-existent asset.
        let handle: Handle<TestDefaults> = Handle::default();
        app.world_mut().insert_resource(DefaultsHandle(handle));

        app.update();

        assert!(
            app.world().get_resource::<TestConfig>().is_none(),
            "TestConfig should not exist when the asset is not loaded"
        );
    }

    /// When the defaults asset is loaded, `seed_config` inserts the
    /// corresponding `Config` resource and reports done progress.
    #[test]
    fn inserts_config_when_asset_loaded() {
        let mut app = test_app();

        let defaults = TestDefaults { value: 99.0 };
        let handle = {
            let mut assets = app.world_mut().resource_mut::<Assets<TestDefaults>>();
            assets.add(defaults)
        };
        app.world_mut().insert_resource(DefaultsHandle(handle));

        app.update();

        let config = app
            .world()
            .get_resource::<TestConfig>()
            .expect("TestConfig should be inserted after seed");
        assert!(
            (config.value - 99.0).abs() < f32::EPSILON,
            "TestConfig.value should be 99.0 from the loaded defaults, got {}",
            config.value
        );
    }

    /// After seeding once, running `seed_config` again does not re-insert
    /// the resource (idempotent). Reports done progress on subsequent ticks.
    #[test]
    fn seed_is_idempotent() {
        let mut app = test_app();

        let defaults = TestDefaults { value: 99.0 };
        let handle = {
            let mut assets = app.world_mut().resource_mut::<Assets<TestDefaults>>();
            assets.add(defaults)
        };
        app.world_mut().insert_resource(DefaultsHandle(handle));

        // First tick — seeds the config.
        app.update();

        // Mutate the config directly to detect re-insertion.
        app.world_mut().resource_mut::<TestConfig>().value = 1.0;

        // Second tick — should NOT re-insert (value stays at 1.0).
        app.update();

        let config = app.world().resource::<TestConfig>();
        assert!(
            (config.value - 1.0).abs() < f32::EPSILON,
            "seed_config should be idempotent — value should remain 1.0, got {}",
            config.value
        );
    }
}

// ── propagate_defaults tests ─────────────────────────────────────

#[cfg(feature = "hot-reload")]
mod propagate_defaults_tests {
    use super::*;

    fn test_app() -> App {
        let mut app = App::new();
        app.add_plugins((MinimalPlugins, AssetPlugin::default()))
            .init_asset::<TestDefaults>()
            .init_resource::<TestConfig>()
            .add_systems(Update, propagate_defaults::<TestDefaults>);
        app
    }

    /// When only an `Added` event fires (no `Modified`), the config
    /// remains unchanged.
    #[test]
    fn config_unchanged_when_no_modified_event() {
        let mut app = test_app();

        let defaults = TestDefaults { value: 10.0 };
        let handle = {
            let mut assets = app.world_mut().resource_mut::<Assets<TestDefaults>>();
            assets.add(defaults)
        };
        app.world_mut().insert_resource(DefaultsHandle(handle));

        // Two updates: PostUpdate flushes Added, First rotates buffer.
        app.update();
        app.update();

        let config = app.world().resource::<TestConfig>();
        assert!(
            (config.value - 0.0).abs() < f32::EPSILON,
            "config should remain at default (0.0) when only Added fires, got {}",
            config.value
        );
    }

    /// When a `Modified` event fires after mutating the asset,
    /// `propagate_defaults` replaces the `Config` resource with new
    /// values.
    #[test]
    fn config_replaced_on_modified_event() {
        let mut app = test_app();

        let defaults = TestDefaults { value: 10.0 };
        let handle = {
            let mut assets = app.world_mut().resource_mut::<Assets<TestDefaults>>();
            assets.add(defaults)
        };
        app.world_mut()
            .insert_resource(DefaultsHandle(handle.clone()));

        // Let Added event settle.
        app.update();
        app.update();

        // Trigger Modified by mutating the asset.
        {
            let mut assets = app.world_mut().resource_mut::<Assets<TestDefaults>>();
            let asset = assets.get_mut(handle.id()).expect("asset should exist");
            asset.value = 77.0;
        }

        // PostUpdate flushes Modified, First rotates buffer, Update runs
        // system.
        app.update();
        app.update();

        let config = app.world().resource::<TestConfig>();
        assert!(
            (config.value - 77.0).abs() < f32::EPSILON,
            "TestConfig.value should be 77.0 after Modified event, got {}",
            config.value
        );
    }
}

// ── init_defaults_handle tests ───────────────────────────────────

mod init_defaults_handle_tests {
    use super::*;

    /// After the startup system runs, `DefaultsHandle<TestDefaults>`
    /// should exist as a resource.
    #[test]
    fn inserts_defaults_handle_on_startup() {
        let mut app = App::new();
        app.add_plugins((MinimalPlugins, AssetPlugin::default()))
            .init_asset::<TestDefaults>()
            .add_systems(Startup, init_defaults_handle::<TestDefaults>);

        app.update();

        assert!(
            app.world()
                .get_resource::<DefaultsHandle<TestDefaults>>()
                .is_some(),
            "DefaultsHandle<TestDefaults> should exist after startup"
        );
    }
}

// ── init_registry_handles tests ───────────────────────────────────

mod init_registry_handles_tests {
    use std::collections::HashMap;

    use serde::Deserialize;

    use super::*;
    use crate::registry::{RegistryHandles, SeedableRegistry};

    #[derive(Asset, TypePath, Deserialize, Clone, Debug)]
    struct TestRegistryAsset {
        name: String,
        value: f32,
    }

    #[derive(Resource, Default, Debug)]
    struct TestRegistry {
        entries: HashMap<String, f32>,
    }

    impl SeedableRegistry for TestRegistry {
        type Asset = TestRegistryAsset;

        fn asset_dir() -> &'static str {
            "test_registry"
        }

        fn extensions() -> &'static [&'static str] {
            &["test.ron"]
        }

        fn seed(&mut self, assets: &[(AssetId<TestRegistryAsset>, TestRegistryAsset)]) {
            self.entries.clear();
            for (_id, asset) in assets {
                self.entries.insert(asset.name.clone(), asset.value);
            }
        }

        fn update_single(&mut self, _id: AssetId<TestRegistryAsset>, asset: &TestRegistryAsset) {
            self.entries.insert(asset.name.clone(), asset.value);
        }
    }

    /// After `init_registry_handles` runs at startup,
    /// `RegistryHandles<TestRegistryAsset>` should exist with
    /// `loaded == false` and empty handles.
    #[test]
    fn inserts_registry_handles_on_startup() {
        let mut app = App::new();
        app.add_plugins((MinimalPlugins, AssetPlugin::default()))
            .init_asset::<TestRegistryAsset>()
            .init_asset::<bevy::asset::LoadedFolder>()
            .add_systems(Startup, init_registry_handles::<TestRegistry>);

        app.update();

        let handles = app
            .world()
            .get_resource::<RegistryHandles<TestRegistryAsset>>()
            .expect("RegistryHandles<TestRegistryAsset> should exist after startup");
        assert!(!handles.loaded, "loaded should be false after init");
        assert!(
            handles.handles.is_empty(),
            "handles should be empty after init"
        );
    }
}

// ── seed_registry tests ───────────────────────────────────────────

#[cfg(feature = "progress")]
mod seed_registry_tests {
    use std::collections::HashMap;

    use serde::Deserialize;

    use super::*;
    use crate::registry::{RegistryHandles, SeedableRegistry};

    #[derive(Asset, TypePath, Deserialize, Clone, Debug)]
    struct TestRegistryAsset {
        name: String,
        value: f32,
    }

    #[derive(Resource, Default, Debug)]
    struct TestRegistry {
        entries: HashMap<String, f32>,
    }

    impl SeedableRegistry for TestRegistry {
        type Asset = TestRegistryAsset;

        fn asset_dir() -> &'static str {
            "test_registry"
        }

        fn extensions() -> &'static [&'static str] {
            &["test.ron"]
        }

        fn seed(&mut self, assets: &[(AssetId<TestRegistryAsset>, TestRegistryAsset)]) {
            self.entries.clear();
            for (_id, asset) in assets {
                self.entries.insert(asset.name.clone(), asset.value);
            }
        }

        fn update_single(&mut self, _id: AssetId<TestRegistryAsset>, asset: &TestRegistryAsset) {
            self.entries.insert(asset.name.clone(), asset.value);
        }
    }

    fn test_app() -> App {
        let mut app = App::new();
        app.add_plugins((MinimalPlugins, AssetPlugin::default()))
            .init_asset::<TestRegistryAsset>()
            .init_asset::<bevy::asset::LoadedFolder>()
            .init_resource::<TestRegistry>()
            .add_systems(Update, seed_registry::<TestRegistry>.map(drop));
        app
    }

    /// Without `RegistryHandles`, `seed_registry` reports zero progress
    /// and the `TestRegistry` stays empty.
    #[test]
    fn returns_zero_progress_when_handles_missing() {
        let mut app = test_app();

        app.update();

        let registry = app.world().resource::<TestRegistry>();
        assert!(
            registry.entries.is_empty(),
            "TestRegistry should remain empty when RegistryHandles is absent"
        );
    }

    /// When `RegistryHandles` exists but folder is not in
    /// `Assets<LoadedFolder>`, `seed_registry` reports zero progress.
    #[test]
    fn returns_zero_progress_when_folder_not_loaded() {
        let mut app = test_app();

        // Insert handles with a default folder handle (pointing to
        // nothing).
        let handles = RegistryHandles::<TestRegistryAsset>::new(Handle::default());
        app.insert_resource(handles);

        app.update();

        let registry = app.world().resource::<TestRegistry>();
        assert!(
            registry.entries.is_empty(),
            "TestRegistry should remain empty when folder is not loaded"
        );
        let rh = app.world().resource::<RegistryHandles<TestRegistryAsset>>();
        assert!(
            !rh.loaded,
            "loaded should remain false when folder not available"
        );
    }

    /// When `LoadedFolder` is available with matching assets,
    /// `seed_registry` resolves the folder, extracts handles, and seeds
    /// the registry.
    #[test]
    fn seeds_registry_when_loaded_folder_available() {
        let mut app = test_app();

        // Create typed assets.
        let (h_alpha, h_beta) = {
            let mut assets = app.world_mut().resource_mut::<Assets<TestRegistryAsset>>();
            let h_alpha = assets.add(TestRegistryAsset {
                name: "alpha".to_string(),
                value: 1.0,
            });
            let h_beta = assets.add(TestRegistryAsset {
                name: "beta".to_string(),
                value: 2.0,
            });
            (h_alpha, h_beta)
        };

        // Create a LoadedFolder containing those handles as untyped.
        let folder_handle = {
            let mut loaded_folders = app
                .world_mut()
                .resource_mut::<Assets<bevy::asset::LoadedFolder>>();
            loaded_folders.add(bevy::asset::LoadedFolder {
                handles: vec![h_alpha.into(), h_beta.into()],
            })
        };

        // Insert RegistryHandles pointing to the loaded folder.
        let mut rh = RegistryHandles::<TestRegistryAsset>::new(folder_handle);
        rh.loaded = false;
        app.insert_resource(rh);

        app.update();

        let registry = app.world().resource::<TestRegistry>();
        assert_eq!(
            registry.entries.len(),
            2,
            "TestRegistry should contain 2 entries"
        );
        assert!(
            (registry.entries["alpha"] - 1.0).abs() < f32::EPSILON,
            "alpha should be 1.0, got {}",
            registry.entries["alpha"]
        );
        assert!(
            (registry.entries["beta"] - 2.0).abs() < f32::EPSILON,
            "beta should be 2.0, got {}",
            registry.entries["beta"]
        );

        let rh = app.world().resource::<RegistryHandles<TestRegistryAsset>>();
        assert!(rh.loaded, "loaded should be true after seeding");
        assert_eq!(rh.handles.len(), 2, "handles should contain 2 entries");
    }

    /// When `RegistryHandles` has `loaded=true` and handles already
    /// populated, `seed_registry` seeds from the pre-loaded handles.
    #[test]
    fn seeds_from_pre_loaded_handles() {
        let mut app = test_app();

        // Create typed assets.
        let (h_alpha, h_beta) = {
            let mut assets = app.world_mut().resource_mut::<Assets<TestRegistryAsset>>();
            let h_alpha = assets.add(TestRegistryAsset {
                name: "alpha".to_string(),
                value: 1.0,
            });
            let h_beta = assets.add(TestRegistryAsset {
                name: "beta".to_string(),
                value: 2.0,
            });
            (h_alpha, h_beta)
        };

        // Insert RegistryHandles with loaded=true and handles already set.
        let mut rh = RegistryHandles::<TestRegistryAsset>::new(Handle::default());
        rh.loaded = true;
        rh.handles = vec![h_alpha, h_beta];
        app.insert_resource(rh);

        app.update();

        let registry = app.world().resource::<TestRegistry>();
        assert_eq!(
            registry.entries.len(),
            2,
            "TestRegistry should contain 2 entries from pre-loaded handles"
        );
        assert!(registry.entries.contains_key("alpha"));
        assert!(registry.entries.contains_key("beta"));
    }

    /// `seed_registry` is idempotent via `Local<bool>` — once seeded,
    /// subsequent updates do not re-seed.
    #[test]
    fn seed_registry_is_idempotent() {
        let mut app = test_app();

        // Create typed assets.
        let (h_alpha, h_beta) = {
            let mut assets = app.world_mut().resource_mut::<Assets<TestRegistryAsset>>();
            let h_alpha = assets.add(TestRegistryAsset {
                name: "alpha".to_string(),
                value: 1.0,
            });
            let h_beta = assets.add(TestRegistryAsset {
                name: "beta".to_string(),
                value: 2.0,
            });
            (h_alpha, h_beta)
        };

        // Insert RegistryHandles with loaded=true.
        let mut rh = RegistryHandles::<TestRegistryAsset>::new(Handle::default());
        rh.loaded = true;
        rh.handles = vec![h_alpha, h_beta];
        app.insert_resource(rh);

        // First tick — seeds.
        app.update();

        // Mutate registry externally.
        app.world_mut()
            .resource_mut::<TestRegistry>()
            .entries
            .insert("extra".to_string(), 999.0);

        // Second tick — should NOT re-seed.
        app.update();

        let registry = app.world().resource::<TestRegistry>();
        assert!(
            registry.entries.contains_key("extra"),
            "extra should still be present — seed_registry should not re-seed"
        );
    }

    /// When handles are loaded but one asset is missing from
    /// `Assets<TestRegistryAsset>`, `seed_registry` does not seed.
    #[test]
    fn returns_zero_when_asset_missing() {
        let mut app = test_app();

        // Create only one asset, but register 2 handles.
        let (h_alpha, h_beta_dangling) = {
            let mut assets = app.world_mut().resource_mut::<Assets<TestRegistryAsset>>();
            let h_alpha = assets.add(TestRegistryAsset {
                name: "alpha".to_string(),
                value: 1.0,
            });
            // Create a handle for beta, then remove the asset to simulate
            // missing.
            let h_beta = assets.add(TestRegistryAsset {
                name: "beta".to_string(),
                value: 2.0,
            });
            let beta_id = h_beta.id();
            assets.remove(beta_id);
            (h_alpha, h_beta)
        };

        let mut rh = RegistryHandles::<TestRegistryAsset>::new(Handle::default());
        rh.loaded = true;
        rh.handles = vec![h_alpha, h_beta_dangling];
        app.insert_resource(rh);

        app.update();

        let registry = app.world().resource::<TestRegistry>();
        assert!(
            registry.entries.is_empty(),
            "TestRegistry should remain empty when an asset is missing"
        );
    }

    /// When `LoadedFolder` is present but contains zero typed handles
    /// (empty folder or all handles filtered by `try_typed`), the registry
    /// should NOT be sealed empty. It should return zero progress and
    /// allow a future retry.
    #[test]
    fn returns_zero_when_folder_has_no_typed_handles() {
        let mut app = test_app();

        // Create a LoadedFolder with no handles at all.
        let folder_handle = {
            let mut folders = app
                .world_mut()
                .resource_mut::<Assets<bevy::asset::LoadedFolder>>();
            folders.add(bevy::asset::LoadedFolder { handles: vec![] })
        };

        let rh = RegistryHandles::<TestRegistryAsset>::new(folder_handle);
        app.insert_resource(rh);

        app.update();

        let registry = app.world().resource::<TestRegistry>();
        assert!(
            registry.entries.is_empty(),
            "TestRegistry should remain empty (no typed handles)"
        );

        // Verify the registry is NOT permanently sealed — loaded should
        // be true (folder was resolved) but seeded should still be false.
        let handles = app.world().resource::<RegistryHandles<TestRegistryAsset>>();
        assert!(
            handles.loaded,
            "loaded should be true (folder was resolved)"
        );
        assert!(
            handles.handles.is_empty(),
            "handles should be empty (no typed handles in folder)"
        );
    }
}

// ── propagate_registry tests ──────────────────────────────────────

#[cfg(feature = "hot-reload")]
mod propagate_registry_tests {
    use std::collections::HashMap;

    use serde::Deserialize;

    use super::*;
    use crate::registry::{RegistryHandles, SeedableRegistry};

    #[derive(Asset, TypePath, Deserialize, Clone, Debug)]
    struct TestRegistryAsset {
        name: String,
        value: f32,
    }

    #[derive(Resource, Default, Debug)]
    struct TestRegistry {
        entries: HashMap<String, f32>,
    }

    impl SeedableRegistry for TestRegistry {
        type Asset = TestRegistryAsset;

        fn asset_dir() -> &'static str {
            "test_registry"
        }

        fn extensions() -> &'static [&'static str] {
            &["test.ron"]
        }

        fn seed(&mut self, assets: &[(AssetId<TestRegistryAsset>, TestRegistryAsset)]) {
            self.entries.clear();
            for (_id, asset) in assets {
                self.entries.insert(asset.name.clone(), asset.value);
            }
        }

        fn update_single(&mut self, _id: AssetId<TestRegistryAsset>, asset: &TestRegistryAsset) {
            self.entries.insert(asset.name.clone(), asset.value);
        }
    }

    fn test_app() -> App {
        let mut app = App::new();
        app.add_plugins((MinimalPlugins, AssetPlugin::default()))
            .init_asset::<TestRegistryAsset>()
            .init_resource::<TestRegistry>()
            .add_systems(Update, propagate_registry::<TestRegistry>);
        app
    }

    /// Helper: creates a test app with a `TestRegistry` pre-seeded with
    /// "alpha" -> 1.0 and `RegistryHandles` with loaded=true pointing to
    /// that asset.
    fn seeded_app() -> (App, Handle<TestRegistryAsset>) {
        let mut app = test_app();

        let h_alpha = {
            let mut assets = app.world_mut().resource_mut::<Assets<TestRegistryAsset>>();
            assets.add(TestRegistryAsset {
                name: "alpha".to_string(),
                value: 1.0,
            })
        };

        // Pre-seed the registry.
        app.world_mut()
            .resource_mut::<TestRegistry>()
            .entries
            .insert("alpha".to_string(), 1.0);

        // Insert RegistryHandles with loaded=true.
        let mut rh = RegistryHandles::<TestRegistryAsset>::new(Handle::default());
        rh.loaded = true;
        rh.handles = vec![h_alpha.clone()];
        app.insert_resource(rh);

        // Let Added event settle (2 updates).
        app.update();
        app.update();

        (app, h_alpha)
    }

    /// When no `AssetEvent::Modified` fires, the registry remains
    /// unchanged.
    #[test]
    fn registry_unchanged_when_no_modified_event() {
        let (mut app, _h_alpha) = seeded_app();

        // One more tick with no mutation.
        app.update();

        let registry = app.world().resource::<TestRegistry>();
        assert_eq!(
            registry.entries.len(),
            1,
            "TestRegistry should still have 1 entry"
        );
        assert!(
            (registry.entries["alpha"] - 1.0).abs() < f32::EPSILON,
            "alpha should still be 1.0, got {}",
            registry.entries["alpha"]
        );
    }

    /// When a `Modified` event fires after mutating the asset,
    /// `propagate_registry` rebuilds the registry with updated values.
    #[test]
    fn registry_rebuilt_on_modified_event() {
        let (mut app, h_alpha) = seeded_app();

        // Mutate the asset to trigger Modified.
        {
            let mut assets = app.world_mut().resource_mut::<Assets<TestRegistryAsset>>();
            let asset = assets.get_mut(h_alpha.id()).expect("asset should exist");
            asset.value = 99.0;
        }

        // PostUpdate flushes Modified, First rotates buffer, Update runs
        // system.
        app.update();
        app.update();

        let registry = app.world().resource::<TestRegistry>();
        assert!(
            (registry.entries["alpha"] - 99.0).abs() < f32::EPSILON,
            "alpha should be 99.0 after Modified event, got {}",
            registry.entries["alpha"]
        );
    }

    /// When a new asset is added (only `Added` event, no `Modified`),
    /// `propagate_registry` does NOT pick up the new asset.
    #[test]
    fn registry_unchanged_on_added_event_only() {
        let (mut app, _h_alpha) = seeded_app();

        // Add a completely new asset (triggers Added, not Modified).
        {
            let mut assets = app.world_mut().resource_mut::<Assets<TestRegistryAsset>>();
            assets.add(TestRegistryAsset {
                name: "beta".to_string(),
                value: 50.0,
            });
        }

        // Let Added settle.
        app.update();
        app.update();

        let registry = app.world().resource::<TestRegistry>();
        assert_eq!(
            registry.entries.len(),
            1,
            "TestRegistry should still have only 1 entry (alpha)"
        );
        assert!(
            !registry.entries.contains_key("beta"),
            "beta should NOT be in the registry after only an Added event"
        );
    }
}
