[alias]
dev = "run -p breaker --features bevy/dynamic_linking"
dbuild = "build -p breaker --features bevy/dynamic_linking"
dtest = "test -p breaker --features bevy/dynamic_linking"
dcheck = "check -p breaker --features bevy/dynamic_linking"
dclippy = "clippy -p breaker --all-targets --features bevy/dynamic_linking"
dscenario = "run -p breaker_scenario_runner"
