//! Tier-based difficulty curve and highlight thresholds — RON-deserialized content data types.

use bevy::prelude::*;
use rantzsoft_defaults::GameConfig;
use serde::Deserialize;

/// The type of a node in the run sequence.
#[derive(Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum NodeType {
    /// A passive node — no active timer pressure.
    Passive,
    /// An active node — timer ticks down during play.
    Active,
    /// A boss node — harder encounter at the end of a tier.
    Boss,
}

/// How many nodes a tier contains — fixed count or a range.
#[derive(Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum TierNodeCount {
    /// Exactly this many nodes.
    Fixed(u32),
    /// Between min and max nodes (inclusive).
    Range(u32, u32),
}

impl TierNodeCount {
    /// Validates that the count specification is well-formed.
    ///
    /// # Errors
    ///
    /// Returns an error string if the range has min greater than max.
    pub fn validate(&self) -> Result<(), String> {
        if let Self::Range(min, max) = self
            && min > max
        {
            return Err(format!(
                "TierNodeCount::Range min ({min}) must not be greater than max ({max})"
            ));
        }
        Ok(())
    }
}

/// Definition of a single difficulty tier loaded from RON.
#[derive(Deserialize, Clone, Debug, PartialEq)]
pub struct TierDefinition {
    /// How many nodes this tier contains.
    pub nodes: TierNodeCount,
    /// Fraction of nodes in this tier that are active (0.0 to 1.0).
    pub active_ratio: f32,
    /// Hit-point multiplier applied to cells in this tier.
    pub hp_mult: f32,
    /// Timer multiplier applied to node timers in this tier.
    pub timer_mult: f32,
    /// Cell-type aliases introduced in this tier.
    pub introduced_cells: Vec<char>,
}

// `DifficultyCurveDefaults` is now generated by the `GameConfig` derive on
// `DifficultyCurve` in `resources.rs`.

/// Highlight detection thresholds loaded from `defaults.highlights.ron`.
///
/// The `GameConfig` derive generates a `HighlightConfig` resource with `From<HighlightDefaults>`.
#[derive(Asset, TypePath, Deserialize, Clone, Debug, GameConfig)]
#[game_config(name = "HighlightConfig")]
pub struct HighlightDefaults {
    /// Seconds remaining for `ClutchClear` detection.
    pub clutch_clear_secs: f32,
    /// Fraction of total time for `FastClear` detection.
    pub fast_clear_fraction: f32,
    /// Consecutive perfect bumps for `PerfectStreak`.
    pub perfect_streak_count: u32,
    /// Cells destroyed in window for `MassDestruction`.
    pub mass_destruction_count: u32,
    /// Window duration (seconds) for `MassDestruction`.
    pub mass_destruction_window_secs: f32,
    /// Cells destroyed between breaker impacts for `ComboKing`.
    pub combo_king_cells: u32,
    /// Cell bounces without breaker for `PinballWizard`.
    pub pinball_wizard_bounces: u32,
    /// Seconds for fastest node clear (`SpeedDemon`).
    pub speed_demon_secs: f32,
    /// Pixels from bottom boundary for `CloseSave`.
    pub close_save_pixels: f32,
    /// Bolts lost in node for `Comeback`.
    pub comeback_bolts_lost: u32,
    /// Pixels from bottom boundary for `NailBiter`.
    pub nail_biter_pixels: f32,
    /// Consecutive no-damage nodes for `Untouchable`.
    pub untouchable_nodes: u32,
    /// Maximum highlights recorded per run.
    pub highlight_cap: u32,

    // -- Popup animation --
    /// Maximum visible highlight popups at once.
    pub popup_max_visible: u32,
    /// Popup fade-out duration (seconds).
    pub popup_fade_duration_secs: f32,
    /// Popup scale overshoot animation duration (seconds).
    pub popup_overshoot_duration_secs: f32,
    /// Popup initial scale overshoot multiplier (e.g. 1.15).
    pub popup_overshoot_scale: f32,
    /// Popup base y-position (above playfield center).
    pub popup_base_y: f32,
    /// Vertical spacing between stacked popups.
    pub popup_vertical_spacing: f32,
    /// Minimum horizontal jitter (pixels, can be negative).
    pub popup_jitter_min_x: f32,
    /// Maximum horizontal jitter (pixels, can be positive).
    pub popup_jitter_max_x: f32,
    /// Cascade stagger delay between simultaneous popups (seconds).
    pub popup_cascade_stagger_secs: f32,

    // -- Scoring --
    /// Diversity penalty base for same-category highlights (0.0–1.0).
    pub diversity_penalty: f32,
    /// Max expected raw score for `ClutchClear` normalization.
    pub max_expected_clutch_clear: f32,
    /// Max expected raw score for `SpeedDemon` normalization.
    pub max_expected_speed_demon: f32,
    /// Max expected raw score for `CloseSave` normalization.
    pub max_expected_close_save: f32,
    /// Max expected raw score for `NailBiter` normalization.
    pub max_expected_nail_biter: f32,
    /// Max expected raw score for `MassDestruction` normalization.
    pub max_expected_mass_destruction: f32,
    /// Max expected raw score for `PerfectStreak` normalization.
    pub max_expected_perfect_streak: f32,
    /// Max expected raw score for `ComboKing` normalization.
    pub max_expected_combo_king: f32,
    /// Max expected raw score for `PinballWizard` normalization.
    pub max_expected_pinball_wizard: f32,
    /// Max expected raw score for `Untouchable` normalization.
    pub max_expected_untouchable: f32,
    /// Max expected raw score for `Comeback` normalization.
    pub max_expected_comeback: f32,
    /// Max expected raw score for `PerfectNode` normalization.
    pub max_expected_perfect_node: f32,
}

impl Default for HighlightDefaults {
    fn default() -> Self {
        Self {
            clutch_clear_secs: 3.0,
            fast_clear_fraction: 0.5,
            perfect_streak_count: 5,
            mass_destruction_count: 10,
            mass_destruction_window_secs: 2.0,
            combo_king_cells: 8,
            pinball_wizard_bounces: 12,
            speed_demon_secs: 5.0,
            close_save_pixels: 20.0,
            comeback_bolts_lost: 3,
            nail_biter_pixels: 30.0,
            untouchable_nodes: 2,
            highlight_cap: 5,
            // Popup animation
            popup_max_visible: 3,
            popup_fade_duration_secs: 0.8,
            popup_overshoot_duration_secs: 0.1,
            popup_overshoot_scale: 1.15,
            popup_base_y: 100.0,
            popup_vertical_spacing: 50.0,
            popup_jitter_min_x: -10.0,
            popup_jitter_max_x: 10.0,
            popup_cascade_stagger_secs: 0.1,
            // Scoring
            diversity_penalty: 0.5,
            max_expected_clutch_clear: 10.0,
            max_expected_speed_demon: 10.0,
            max_expected_close_save: 10.0,
            max_expected_nail_biter: 10.0,
            max_expected_mass_destruction: 5.0,
            max_expected_perfect_streak: 4.0,
            max_expected_combo_king: 4.0,
            max_expected_pinball_wizard: 4.0,
            max_expected_untouchable: 5.0,
            max_expected_comeback: 3.0,
            max_expected_perfect_node: 20.0,
        }
    }
}
