//! Shared constants for the RNG migration audit tests.
//!
//! Holds the forbidden identifier and the snapshot list of production files
//! to scan. `include_str!` paths are relative to THIS FILE's location
//! (`src/shared/rng_migration_audit/`), so paths reach one level up via `../`
//! to enter `src/shared/`, and two levels up via `../../` to reach `src/`.

// The forbidden identifier is built at compile time to avoid a self-referential
// false-positive where include_str finds the guard string in this file.
pub(super) const GAME_RNG: &str = concat!("Game", "Rng");

// Each entry is (relative_path_from_src, file_content).
// The relative path is used only in assertion messages (not for file resolution).
// include_str! paths are relative to THIS FILE's location (src/shared/rng_migration_audit/).
// Files at src/ level need "../../", files inside src/shared/ need "../".
//
// Production files only — excludes tests/, *_tests.rs, tests.rs, shared/test_utils/*.
pub(super) const PRODUCTION_FILES: &[(&str, &str)] = &[
    ("app.rs", include_str!("../../app.rs")),
    ("audio/mod.rs", include_str!("../../audio/mod.rs")),
    ("audio/plugin.rs", include_str!("../../audio/plugin.rs")),
    (
        "bolt/builder/core/mod.rs",
        include_str!("../../bolt/builder/core/mod.rs"),
    ),
    (
        "bolt/builder/core/terminal.rs",
        include_str!("../../bolt/builder/core/terminal.rs"),
    ),
    (
        "bolt/builder/core/transitions.rs",
        include_str!("../../bolt/builder/core/transitions.rs"),
    ),
    (
        "bolt/builder/core/types.rs",
        include_str!("../../bolt/builder/core/types.rs"),
    ),
    (
        "bolt/builder/mod.rs",
        include_str!("../../bolt/builder/mod.rs"),
    ),
    (
        "bolt/components/definitions.rs",
        include_str!("../../bolt/components/definitions.rs"),
    ),
    (
        "bolt/components/mod.rs",
        include_str!("../../bolt/components/mod.rs"),
    ),
    (
        "bolt/components/phantom/inner.rs",
        include_str!("../../bolt/components/phantom/inner.rs"),
    ),
    (
        "bolt/components/phantom/mod.rs",
        include_str!("../../bolt/components/phantom/mod.rs"),
    ),
    (
        "bolt/definition.rs",
        include_str!("../../bolt/definition.rs"),
    ),
    ("bolt/filters.rs", include_str!("../../bolt/filters.rs")),
    ("bolt/messages.rs", include_str!("../../bolt/messages.rs")),
    ("bolt/mod.rs", include_str!("../../bolt/mod.rs")),
    ("bolt/plugin.rs", include_str!("../../bolt/plugin.rs")),
    ("bolt/queries.rs", include_str!("../../bolt/queries.rs")),
    (
        "bolt/registry/data.rs",
        include_str!("../../bolt/registry/data.rs"),
    ),
    (
        "bolt/registry/mod.rs",
        include_str!("../../bolt/registry/mod.rs"),
    ),
    ("bolt/resources.rs", include_str!("../../bolt/resources.rs")),
    ("bolt/sets.rs", include_str!("../../bolt/sets.rs")),
    (
        "bolt/systems/apply_bolt_forces/mod.rs",
        include_str!("../../bolt/systems/apply_bolt_forces/mod.rs"),
    ),
    (
        "bolt/systems/apply_bolt_forces/system.rs",
        include_str!("../../bolt/systems/apply_bolt_forces/system.rs"),
    ),
    (
        "bolt/systems/begin_node_birthing.rs",
        include_str!("../../bolt/systems/begin_node_birthing.rs"),
    ),
    (
        "bolt/systems/bolt_breaker_collision/mod.rs",
        include_str!("../../bolt/systems/bolt_breaker_collision/mod.rs"),
    ),
    (
        "bolt/systems/bolt_breaker_collision/system.rs",
        include_str!("../../bolt/systems/bolt_breaker_collision/system.rs"),
    ),
    (
        "bolt/systems/bolt_cell_collision/mod.rs",
        include_str!("../../bolt/systems/bolt_cell_collision/mod.rs"),
    ),
    (
        "bolt/systems/bolt_cell_collision/system.rs",
        include_str!("../../bolt/systems/bolt_cell_collision/system.rs"),
    ),
    (
        "bolt/systems/bolt_lost_feedback.rs",
        include_str!("../../bolt/systems/bolt_lost_feedback.rs"),
    ),
    (
        "bolt/systems/bolt_lost/mod.rs",
        include_str!("../../bolt/systems/bolt_lost/mod.rs"),
    ),
    (
        "bolt/systems/bolt_lost/system.rs",
        include_str!("../../bolt/systems/bolt_lost/system.rs"),
    ),
    (
        "bolt/systems/bolt_wall_collision/mod.rs",
        include_str!("../../bolt/systems/bolt_wall_collision/mod.rs"),
    ),
    (
        "bolt/systems/bolt_wall_collision/system.rs",
        include_str!("../../bolt/systems/bolt_wall_collision/system.rs"),
    ),
    (
        "bolt/systems/clamp_bolt_to_playfield/mod.rs",
        include_str!("../../bolt/systems/clamp_bolt_to_playfield/mod.rs"),
    ),
    (
        "bolt/systems/clamp_bolt_to_playfield/system.rs",
        include_str!("../../bolt/systems/clamp_bolt_to_playfield/system.rs"),
    ),
    (
        "bolt/systems/dispatch_bolt_effects/mod.rs",
        include_str!("../../bolt/systems/dispatch_bolt_effects/mod.rs"),
    ),
    (
        "bolt/systems/dispatch_bolt_effects/system.rs",
        include_str!("../../bolt/systems/dispatch_bolt_effects/system.rs"),
    ),
    (
        "bolt/systems/hover_bolt.rs",
        include_str!("../../bolt/systems/hover_bolt.rs"),
    ),
    (
        "bolt/systems/launch_bolt/mod.rs",
        include_str!("../../bolt/systems/launch_bolt/mod.rs"),
    ),
    (
        "bolt/systems/launch_bolt/system.rs",
        include_str!("../../bolt/systems/launch_bolt/system.rs"),
    ),
    (
        "bolt/systems/mod.rs",
        include_str!("../../bolt/systems/mod.rs"),
    ),
    (
        "bolt/systems/normalize_speed_after_constraints.rs",
        include_str!("../../bolt/systems/normalize_speed_after_constraints.rs"),
    ),
    (
        "bolt/systems/sync_bolt_scale/mod.rs",
        include_str!("../../bolt/systems/sync_bolt_scale/mod.rs"),
    ),
    (
        "bolt/systems/sync_bolt_scale/system.rs",
        include_str!("../../bolt/systems/sync_bolt_scale/system.rs"),
    ),
    (
        "bolt/systems/sync_bolt_speed_to_stack.rs",
        include_str!("../../bolt/systems/sync_bolt_speed_to_stack.rs"),
    ),
    (
        "bolt/systems/tick_birthing/mod.rs",
        include_str!("../../bolt/systems/tick_birthing/mod.rs"),
    ),
    (
        "bolt/systems/tick_birthing/system.rs",
        include_str!("../../bolt/systems/tick_birthing/system.rs"),
    ),
    (
        "bolt/systems/tick_bolt_lifespan/mod.rs",
        include_str!("../../bolt/systems/tick_bolt_lifespan/mod.rs"),
    ),
    (
        "bolt/systems/tick_bolt_lifespan/system.rs",
        include_str!("../../bolt/systems/tick_bolt_lifespan/system.rs"),
    ),
    (
        "bolt/test_utils.rs",
        include_str!("../../bolt/test_utils.rs"),
    ),
    (
        "breaker/builder/core/mod.rs",
        include_str!("../../breaker/builder/core/mod.rs"),
    ),
    (
        "breaker/builder/core/terminal.rs",
        include_str!("../../breaker/builder/core/terminal.rs"),
    ),
    (
        "breaker/builder/core/transitions.rs",
        include_str!("../../breaker/builder/core/transitions.rs"),
    ),
    (
        "breaker/builder/core/types.rs",
        include_str!("../../breaker/builder/core/types.rs"),
    ),
    (
        "breaker/builder/mod.rs",
        include_str!("../../breaker/builder/mod.rs"),
    ),
    (
        "breaker/components/bolt_loss_behavior.rs",
        include_str!("../../breaker/components/bolt_loss_behavior.rs"),
    ),
    (
        "breaker/components/bump.rs",
        include_str!("../../breaker/components/bump.rs"),
    ),
    (
        "breaker/components/core.rs",
        include_str!("../../breaker/components/core.rs"),
    ),
    (
        "breaker/components/dash.rs",
        include_str!("../../breaker/components/dash.rs"),
    ),
    (
        "breaker/components/mod.rs",
        include_str!("../../breaker/components/mod.rs"),
    ),
    (
        "breaker/components/movement.rs",
        include_str!("../../breaker/components/movement.rs"),
    ),
    (
        "breaker/components/previous_dash_state.rs",
        include_str!("../../breaker/components/previous_dash_state.rs"),
    ),
    (
        "breaker/components/state.rs",
        include_str!("../../breaker/components/state.rs"),
    ),
    (
        "breaker/definition/mod.rs",
        include_str!("../../breaker/definition/mod.rs"),
    ),
    (
        "breaker/definition/types.rs",
        include_str!("../../breaker/definition/types.rs"),
    ),
    (
        "breaker/filters.rs",
        include_str!("../../breaker/filters.rs"),
    ),
    (
        "breaker/messages.rs",
        include_str!("../../breaker/messages.rs"),
    ),
    ("breaker/mod.rs", include_str!("../../breaker/mod.rs")),
    ("breaker/plugin.rs", include_str!("../../breaker/plugin.rs")),
    (
        "breaker/queries/data.rs",
        include_str!("../../breaker/queries/data.rs"),
    ),
    (
        "breaker/queries/mod.rs",
        include_str!("../../breaker/queries/mod.rs"),
    ),
    (
        "breaker/registry.rs",
        include_str!("../../breaker/registry.rs"),
    ),
    (
        "breaker/resources.rs",
        include_str!("../../breaker/resources.rs"),
    ),
    ("breaker/sets.rs", include_str!("../../breaker/sets.rs")),
    (
        "breaker/systems/breaker_cell_collision.rs",
        include_str!("../../breaker/systems/breaker_cell_collision.rs"),
    ),
    (
        "breaker/systems/breaker_wall_collision/mod.rs",
        include_str!("../../breaker/systems/breaker_wall_collision/mod.rs"),
    ),
    (
        "breaker/systems/breaker_wall_collision/system.rs",
        include_str!("../../breaker/systems/breaker_wall_collision/system.rs"),
    ),
    (
        "breaker/systems/bump_feedback.rs",
        include_str!("../../breaker/systems/bump_feedback.rs"),
    ),
    (
        "breaker/systems/bump_visual/mod.rs",
        include_str!("../../breaker/systems/bump_visual/mod.rs"),
    ),
    (
        "breaker/systems/bump_visual/system.rs",
        include_str!("../../breaker/systems/bump_visual/system.rs"),
    ),
    (
        "breaker/systems/bump/mod.rs",
        include_str!("../../breaker/systems/bump/mod.rs"),
    ),
    (
        "breaker/systems/bump/system.rs",
        include_str!("../../breaker/systems/bump/system.rs"),
    ),
    (
        "breaker/systems/dash/mod.rs",
        include_str!("../../breaker/systems/dash/mod.rs"),
    ),
    (
        "breaker/systems/dash/system.rs",
        include_str!("../../breaker/systems/dash/system.rs"),
    ),
    (
        "breaker/systems/handle_bolt_lost/mod.rs",
        include_str!("../../breaker/systems/handle_bolt_lost/mod.rs"),
    ),
    (
        "breaker/systems/handle_bolt_lost/system.rs",
        include_str!("../../breaker/systems/handle_bolt_lost/system.rs"),
    ),
    (
        "breaker/systems/mod.rs",
        include_str!("../../breaker/systems/mod.rs"),
    ),
    (
        "breaker/systems/move_breaker/mod.rs",
        include_str!("../../breaker/systems/move_breaker/mod.rs"),
    ),
    (
        "breaker/systems/move_breaker/system.rs",
        include_str!("../../breaker/systems/move_breaker/system.rs"),
    ),
    (
        "breaker/systems/spawn_breaker/mod.rs",
        include_str!("../../breaker/systems/spawn_breaker/mod.rs"),
    ),
    (
        "breaker/systems/sync_breaker_scale/mod.rs",
        include_str!("../../breaker/systems/sync_breaker_scale/mod.rs"),
    ),
    (
        "breaker/systems/sync_breaker_scale/system.rs",
        include_str!("../../breaker/systems/sync_breaker_scale/system.rs"),
    ),
    (
        "breaker/systems/tick_phantom_breaker_lifespan/mod.rs",
        include_str!("../../breaker/systems/tick_phantom_breaker_lifespan/mod.rs"),
    ),
    (
        "breaker/systems/tick_phantom_breaker_lifespan/system.rs",
        include_str!("../../breaker/systems/tick_phantom_breaker_lifespan/system.rs"),
    ),
    (
        "breaker/systems/tilt_visual.rs",
        include_str!("../../breaker/systems/tilt_visual.rs"),
    ),
    (
        "breaker/systems/update_previous_dash_state/mod.rs",
        include_str!("../../breaker/systems/update_previous_dash_state/mod.rs"),
    ),
    (
        "breaker/systems/update_previous_dash_state/system.rs",
        include_str!("../../breaker/systems/update_previous_dash_state/system.rs"),
    ),
    (
        "breaker/test_utils.rs",
        include_str!("../../breaker/test_utils.rs"),
    ),
    (
        "cells/behaviors/armored/components.rs",
        include_str!("../../cells/behaviors/armored/components.rs"),
    ),
    (
        "cells/behaviors/armored/mod.rs",
        include_str!("../../cells/behaviors/armored/mod.rs"),
    ),
    (
        "cells/behaviors/armored/systems/check_armor_direction.rs",
        include_str!("../../cells/behaviors/armored/systems/check_armor_direction.rs"),
    ),
    (
        "cells/behaviors/armored/systems/mod.rs",
        include_str!("../../cells/behaviors/armored/systems/mod.rs"),
    ),
    (
        "cells/behaviors/guarded/components.rs",
        include_str!("../../cells/behaviors/guarded/components.rs"),
    ),
    (
        "cells/behaviors/guarded/mod.rs",
        include_str!("../../cells/behaviors/guarded/mod.rs"),
    ),
    (
        "cells/behaviors/guarded/systems/mod.rs",
        include_str!("../../cells/behaviors/guarded/systems/mod.rs"),
    ),
    (
        "cells/behaviors/guarded/systems/slide_guardian_cells/mod.rs",
        include_str!("../../cells/behaviors/guarded/systems/slide_guardian_cells/mod.rs"),
    ),
    (
        "cells/behaviors/guarded/systems/slide_guardian_cells/system.rs",
        include_str!("../../cells/behaviors/guarded/systems/slide_guardian_cells/system.rs"),
    ),
    (
        "cells/behaviors/locked/components.rs",
        include_str!("../../cells/behaviors/locked/components.rs"),
    ),
    (
        "cells/behaviors/locked/mod.rs",
        include_str!("../../cells/behaviors/locked/mod.rs"),
    ),
    (
        "cells/behaviors/locked/systems/check_lock_release/mod.rs",
        include_str!("../../cells/behaviors/locked/systems/check_lock_release/mod.rs"),
    ),
    (
        "cells/behaviors/locked/systems/check_lock_release/system.rs",
        include_str!("../../cells/behaviors/locked/systems/check_lock_release/system.rs"),
    ),
    (
        "cells/behaviors/locked/systems/mod.rs",
        include_str!("../../cells/behaviors/locked/systems/mod.rs"),
    ),
    (
        "cells/behaviors/locked/systems/sync_lock_invulnerable.rs",
        include_str!("../../cells/behaviors/locked/systems/sync_lock_invulnerable.rs"),
    ),
    (
        "cells/behaviors/magnetic/components.rs",
        include_str!("../../cells/behaviors/magnetic/components.rs"),
    ),
    (
        "cells/behaviors/magnetic/mod.rs",
        include_str!("../../cells/behaviors/magnetic/mod.rs"),
    ),
    (
        "cells/behaviors/magnetic/systems/apply_magnetic_fields.rs",
        include_str!("../../cells/behaviors/magnetic/systems/apply_magnetic_fields.rs"),
    ),
    (
        "cells/behaviors/magnetic/systems/mod.rs",
        include_str!("../../cells/behaviors/magnetic/systems/mod.rs"),
    ),
    (
        "cells/behaviors/mod.rs",
        include_str!("../../cells/behaviors/mod.rs"),
    ),
    (
        "cells/behaviors/phantom/components.rs",
        include_str!("../../cells/behaviors/phantom/components.rs"),
    ),
    (
        "cells/behaviors/phantom/mod.rs",
        include_str!("../../cells/behaviors/phantom/mod.rs"),
    ),
    (
        "cells/behaviors/phantom/systems/mod.rs",
        include_str!("../../cells/behaviors/phantom/systems/mod.rs"),
    ),
    (
        "cells/behaviors/phantom/systems/tick_phantom_phase.rs",
        include_str!("../../cells/behaviors/phantom/systems/tick_phantom_phase.rs"),
    ),
    (
        "cells/behaviors/portal/components.rs",
        include_str!("../../cells/behaviors/portal/components.rs"),
    ),
    (
        "cells/behaviors/portal/mod.rs",
        include_str!("../../cells/behaviors/portal/mod.rs"),
    ),
    (
        "cells/behaviors/portal/systems/check_portal_entry/mod.rs",
        include_str!("../../cells/behaviors/portal/systems/check_portal_entry/mod.rs"),
    ),
    (
        "cells/behaviors/portal/systems/check_portal_entry/system.rs",
        include_str!("../../cells/behaviors/portal/systems/check_portal_entry/system.rs"),
    ),
    (
        "cells/behaviors/portal/systems/handle_portal_completed/mod.rs",
        include_str!("../../cells/behaviors/portal/systems/handle_portal_completed/mod.rs"),
    ),
    (
        "cells/behaviors/portal/systems/handle_portal_completed/system.rs",
        include_str!("../../cells/behaviors/portal/systems/handle_portal_completed/system.rs"),
    ),
    (
        "cells/behaviors/portal/systems/handle_portal_entered/mod.rs",
        include_str!("../../cells/behaviors/portal/systems/handle_portal_entered/mod.rs"),
    ),
    (
        "cells/behaviors/portal/systems/handle_portal_entered/system.rs",
        include_str!("../../cells/behaviors/portal/systems/handle_portal_entered/system.rs"),
    ),
    (
        "cells/behaviors/portal/systems/mod.rs",
        include_str!("../../cells/behaviors/portal/systems/mod.rs"),
    ),
    (
        "cells/behaviors/regen/components.rs",
        include_str!("../../cells/behaviors/regen/components.rs"),
    ),
    (
        "cells/behaviors/regen/mod.rs",
        include_str!("../../cells/behaviors/regen/mod.rs"),
    ),
    (
        "cells/behaviors/regen/systems/mod.rs",
        include_str!("../../cells/behaviors/regen/systems/mod.rs"),
    ),
    (
        "cells/behaviors/regen/systems/tick_cell_regen.rs",
        include_str!("../../cells/behaviors/regen/systems/tick_cell_regen.rs"),
    ),
    (
        "cells/behaviors/sequence/components.rs",
        include_str!("../../cells/behaviors/sequence/components.rs"),
    ),
    (
        "cells/behaviors/sequence/mod.rs",
        include_str!("../../cells/behaviors/sequence/mod.rs"),
    ),
    (
        "cells/behaviors/sequence/systems/advance_sequence.rs",
        include_str!("../../cells/behaviors/sequence/systems/advance_sequence.rs"),
    ),
    (
        "cells/behaviors/sequence/systems/init_sequence_groups.rs",
        include_str!("../../cells/behaviors/sequence/systems/init_sequence_groups.rs"),
    ),
    (
        "cells/behaviors/sequence/systems/mod.rs",
        include_str!("../../cells/behaviors/sequence/systems/mod.rs"),
    ),
    (
        "cells/behaviors/sequence/systems/reset_inactive_sequence_hp.rs",
        include_str!("../../cells/behaviors/sequence/systems/reset_inactive_sequence_hp.rs"),
    ),
    (
        "cells/behaviors/survival/components.rs",
        include_str!("../../cells/behaviors/survival/components.rs"),
    ),
    (
        "cells/behaviors/survival/mod.rs",
        include_str!("../../cells/behaviors/survival/mod.rs"),
    ),
    (
        "cells/behaviors/survival/salvo/components.rs",
        include_str!("../../cells/behaviors/survival/salvo/components.rs"),
    ),
    (
        "cells/behaviors/survival/salvo/mod.rs",
        include_str!("../../cells/behaviors/survival/salvo/mod.rs"),
    ),
    (
        "cells/behaviors/survival/salvo/systems/fire_survival_turret.rs",
        include_str!("../../cells/behaviors/survival/salvo/systems/fire_survival_turret.rs"),
    ),
    (
        "cells/behaviors/survival/salvo/systems/mod.rs",
        include_str!("../../cells/behaviors/survival/salvo/systems/mod.rs"),
    ),
    (
        "cells/behaviors/survival/salvo/systems/salvo_bolt_collision.rs",
        include_str!("../../cells/behaviors/survival/salvo/systems/salvo_bolt_collision.rs"),
    ),
    (
        "cells/behaviors/survival/salvo/systems/salvo_breaker_collision.rs",
        include_str!("../../cells/behaviors/survival/salvo/systems/salvo_breaker_collision.rs"),
    ),
    (
        "cells/behaviors/survival/salvo/systems/salvo_cell_collision.rs",
        include_str!("../../cells/behaviors/survival/salvo/systems/salvo_cell_collision.rs"),
    ),
    (
        "cells/behaviors/survival/salvo/systems/salvo_wall_collision.rs",
        include_str!("../../cells/behaviors/survival/salvo/systems/salvo_wall_collision.rs"),
    ),
    (
        "cells/behaviors/survival/salvo/systems/tick_salvo_fire_timer.rs",
        include_str!("../../cells/behaviors/survival/salvo/systems/tick_salvo_fire_timer.rs"),
    ),
    (
        "cells/behaviors/survival/salvo/systems/tick_survival_timer.rs",
        include_str!("../../cells/behaviors/survival/salvo/systems/tick_survival_timer.rs"),
    ),
    (
        "cells/behaviors/survival/systems/mod.rs",
        include_str!("../../cells/behaviors/survival/systems/mod.rs"),
    ),
    (
        "cells/behaviors/survival/systems/suppress_bolt_immune_damage.rs",
        include_str!("../../cells/behaviors/survival/systems/suppress_bolt_immune_damage.rs"),
    ),
    (
        "cells/behaviors/volatile/components.rs",
        include_str!("../../cells/behaviors/volatile/components.rs"),
    ),
    (
        "cells/behaviors/volatile/mod.rs",
        include_str!("../../cells/behaviors/volatile/mod.rs"),
    ),
    (
        "cells/behaviors/volatile/stamp.rs",
        include_str!("../../cells/behaviors/volatile/stamp.rs"),
    ),
    (
        "cells/builder/core/mod.rs",
        include_str!("../../cells/builder/core/mod.rs"),
    ),
    (
        "cells/builder/core/terminal.rs",
        include_str!("../../cells/builder/core/terminal.rs"),
    ),
    (
        "cells/builder/core/transitions.rs",
        include_str!("../../cells/builder/core/transitions.rs"),
    ),
    (
        "cells/builder/core/types.rs",
        include_str!("../../cells/builder/core/types.rs"),
    ),
    (
        "cells/builder/mod.rs",
        include_str!("../../cells/builder/mod.rs"),
    ),
    (
        "cells/components/adjacency.rs",
        include_str!("../../cells/components/adjacency.rs"),
    ),
    (
        "cells/components/mod.rs",
        include_str!("../../cells/components/mod.rs"),
    ),
    (
        "cells/components/types.rs",
        include_str!("../../cells/components/types.rs"),
    ),
    (
        "cells/definition/data.rs",
        include_str!("../../cells/definition/data.rs"),
    ),
    (
        "cells/definition/mod.rs",
        include_str!("../../cells/definition/mod.rs"),
    ),
    ("cells/filters.rs", include_str!("../../cells/filters.rs")),
    ("cells/messages.rs", include_str!("../../cells/messages.rs")),
    ("cells/mod.rs", include_str!("../../cells/mod.rs")),
    (
        "cells/plugin/mod.rs",
        include_str!("../../cells/plugin/mod.rs"),
    ),
    (
        "cells/plugin/system.rs",
        include_str!("../../cells/plugin/system.rs"),
    ),
    (
        "cells/resources/data.rs",
        include_str!("../../cells/resources/data.rs"),
    ),
    (
        "cells/resources/mod.rs",
        include_str!("../../cells/resources/mod.rs"),
    ),
    (
        "cells/systems/cell_wall_collision.rs",
        include_str!("../../cells/systems/cell_wall_collision.rs"),
    ),
    (
        "cells/systems/mod.rs",
        include_str!("../../cells/systems/mod.rs"),
    ),
    (
        "cells/systems/update_cell_damage_visuals.rs",
        include_str!("../../cells/systems/update_cell_damage_visuals.rs"),
    ),
    (
        "cells/test_utils.rs",
        include_str!("../../cells/test_utils.rs"),
    ),
    (
        "chips/components.rs",
        include_str!("../../chips/components.rs"),
    ),
    (
        "chips/definition/mod.rs",
        include_str!("../../chips/definition/mod.rs"),
    ),
    (
        "chips/definition/types.rs",
        include_str!("../../chips/definition/types.rs"),
    ),
    (
        "chips/inventory/data.rs",
        include_str!("../../chips/inventory/data.rs"),
    ),
    (
        "chips/inventory/mod.rs",
        include_str!("../../chips/inventory/mod.rs"),
    ),
    ("chips/mod.rs", include_str!("../../chips/mod.rs")),
    (
        "chips/offering/mod.rs",
        include_str!("../../chips/offering/mod.rs"),
    ),
    (
        "chips/offering/system.rs",
        include_str!("../../chips/offering/system.rs"),
    ),
    ("chips/plugin.rs", include_str!("../../chips/plugin.rs")),
    (
        "chips/resources/data.rs",
        include_str!("../../chips/resources/data.rs"),
    ),
    (
        "chips/resources/mod.rs",
        include_str!("../../chips/resources/mod.rs"),
    ),
    (
        "chips/systems/build_chip_catalog/mod.rs",
        include_str!("../../chips/systems/build_chip_catalog/mod.rs"),
    ),
    (
        "chips/systems/build_chip_catalog/system.rs",
        include_str!("../../chips/systems/build_chip_catalog/system.rs"),
    ),
    (
        "chips/systems/dispatch_chip_effects/mod.rs",
        include_str!("../../chips/systems/dispatch_chip_effects/mod.rs"),
    ),
    (
        "chips/systems/dispatch_chip_effects/system.rs",
        include_str!("../../chips/systems/dispatch_chip_effects/system.rs"),
    ),
    (
        "chips/systems/mod.rs",
        include_str!("../../chips/systems/mod.rs"),
    ),
    (
        "debug/hot_reload/mod.rs",
        include_str!("../../debug/hot_reload/mod.rs"),
    ),
    (
        "debug/hot_reload/plugin.rs",
        include_str!("../../debug/hot_reload/plugin.rs"),
    ),
    (
        "debug/hot_reload/sets.rs",
        include_str!("../../debug/hot_reload/sets.rs"),
    ),
    (
        "debug/hot_reload/systems/mod.rs",
        include_str!("../../debug/hot_reload/systems/mod.rs"),
    ),
    (
        "debug/hot_reload/systems/propagate_bolt_definition/mod.rs",
        include_str!("../../debug/hot_reload/systems/propagate_bolt_definition/mod.rs"),
    ),
    (
        "debug/hot_reload/systems/propagate_bolt_definition/system.rs",
        include_str!("../../debug/hot_reload/systems/propagate_bolt_definition/system.rs"),
    ),
    (
        "debug/hot_reload/systems/propagate_breaker_changes/mod.rs",
        include_str!("../../debug/hot_reload/systems/propagate_breaker_changes/mod.rs"),
    ),
    (
        "debug/hot_reload/systems/propagate_breaker_changes/system.rs",
        include_str!("../../debug/hot_reload/systems/propagate_breaker_changes/system.rs"),
    ),
    (
        "debug/hot_reload/systems/propagate_cell_type_changes.rs",
        include_str!("../../debug/hot_reload/systems/propagate_cell_type_changes.rs"),
    ),
    (
        "debug/hot_reload/systems/propagate_node_layout_changes.rs",
        include_str!("../../debug/hot_reload/systems/propagate_node_layout_changes.rs"),
    ),
    ("debug/mod.rs", include_str!("../../debug/mod.rs")),
    (
        "debug/overlays/mod.rs",
        include_str!("../../debug/overlays/mod.rs"),
    ),
    (
        "debug/overlays/plugin.rs",
        include_str!("../../debug/overlays/plugin.rs"),
    ),
    (
        "debug/overlays/systems/draw_hitboxes.rs",
        include_str!("../../debug/overlays/systems/draw_hitboxes.rs"),
    ),
    (
        "debug/overlays/systems/draw_velocity_vectors.rs",
        include_str!("../../debug/overlays/systems/draw_velocity_vectors.rs"),
    ),
    (
        "debug/overlays/systems/mod.rs",
        include_str!("../../debug/overlays/systems/mod.rs"),
    ),
    ("debug/plugin.rs", include_str!("../../debug/plugin.rs")),
    (
        "debug/recording/mod.rs",
        include_str!("../../debug/recording/mod.rs"),
    ),
    (
        "debug/recording/plugin.rs",
        include_str!("../../debug/recording/plugin.rs"),
    ),
    (
        "debug/recording/resources.rs",
        include_str!("../../debug/recording/resources.rs"),
    ),
    (
        "debug/recording/systems/capture_frame.rs",
        include_str!("../../debug/recording/systems/capture_frame.rs"),
    ),
    (
        "debug/recording/systems/mod.rs",
        include_str!("../../debug/recording/systems/mod.rs"),
    ),
    (
        "debug/recording/systems/write_output.rs",
        include_str!("../../debug/recording/systems/write_output.rs"),
    ),
    (
        "debug/resources.rs",
        include_str!("../../debug/resources.rs"),
    ),
    (
        "debug/telemetry/mod.rs",
        include_str!("../../debug/telemetry/mod.rs"),
    ),
    (
        "debug/telemetry/plugin.rs",
        include_str!("../../debug/telemetry/plugin.rs"),
    ),
    (
        "debug/telemetry/systems/bolt_info_ui.rs",
        include_str!("../../debug/telemetry/systems/bolt_info_ui.rs"),
    ),
    (
        "debug/telemetry/systems/breaker_state_ui.rs",
        include_str!("../../debug/telemetry/systems/breaker_state_ui.rs"),
    ),
    (
        "debug/telemetry/systems/debug_ui.rs",
        include_str!("../../debug/telemetry/systems/debug_ui.rs"),
    ),
    (
        "debug/telemetry/systems/input_actions_ui.rs",
        include_str!("../../debug/telemetry/systems/input_actions_ui.rs"),
    ),
    (
        "debug/telemetry/systems/mod.rs",
        include_str!("../../debug/telemetry/systems/mod.rs"),
    ),
    (
        "debug/telemetry/systems/track_bump_result.rs",
        include_str!("../../debug/telemetry/systems/track_bump_result.rs"),
    ),
    (
        "effect_v3/commands/ext/mod.rs",
        include_str!("../../effect_v3/commands/ext/mod.rs"),
    ),
    (
        "effect_v3/commands/ext/system.rs",
        include_str!("../../effect_v3/commands/ext/system.rs"),
    ),
    (
        "effect_v3/commands/fire.rs",
        include_str!("../../effect_v3/commands/fire.rs"),
    ),
    (
        "effect_v3/commands/mod.rs",
        include_str!("../../effect_v3/commands/mod.rs"),
    ),
    (
        "effect_v3/commands/remove_staged.rs",
        include_str!("../../effect_v3/commands/remove_staged.rs"),
    ),
    (
        "effect_v3/commands/remove.rs",
        include_str!("../../effect_v3/commands/remove.rs"),
    ),
    (
        "effect_v3/commands/reverse.rs",
        include_str!("../../effect_v3/commands/reverse.rs"),
    ),
    (
        "effect_v3/commands/route.rs",
        include_str!("../../effect_v3/commands/route.rs"),
    ),
    (
        "effect_v3/commands/stage.rs",
        include_str!("../../effect_v3/commands/stage.rs"),
    ),
    (
        "effect_v3/commands/stamp.rs",
        include_str!("../../effect_v3/commands/stamp.rs"),
    ),
    (
        "effect_v3/commands/track_armed_fire.rs",
        include_str!("../../effect_v3/commands/track_armed_fire.rs"),
    ),
    (
        "effect_v3/components/effect_source_chip.rs",
        include_str!("../../effect_v3/components/effect_source_chip.rs"),
    ),
    (
        "effect_v3/components/mod.rs",
        include_str!("../../effect_v3/components/mod.rs"),
    ),
    (
        "effect_v3/conditions/combo_active.rs",
        include_str!("../../effect_v3/conditions/combo_active.rs"),
    ),
    (
        "effect_v3/conditions/evaluate_conditions/mod.rs",
        include_str!("../../effect_v3/conditions/evaluate_conditions/mod.rs"),
    ),
    (
        "effect_v3/conditions/evaluate_conditions/system.rs",
        include_str!("../../effect_v3/conditions/evaluate_conditions/system.rs"),
    ),
    (
        "effect_v3/conditions/mod.rs",
        include_str!("../../effect_v3/conditions/mod.rs"),
    ),
    (
        "effect_v3/conditions/node_active.rs",
        include_str!("../../effect_v3/conditions/node_active.rs"),
    ),
    (
        "effect_v3/conditions/shield_active.rs",
        include_str!("../../effect_v3/conditions/shield_active.rs"),
    ),
    (
        "effect_v3/dispatch/fire_dispatch.rs",
        include_str!("../../effect_v3/dispatch/fire_dispatch.rs"),
    ),
    (
        "effect_v3/dispatch/mod.rs",
        include_str!("../../effect_v3/dispatch/mod.rs"),
    ),
    (
        "effect_v3/dispatch/reverse_dispatch/mod.rs",
        include_str!("../../effect_v3/dispatch/reverse_dispatch/mod.rs"),
    ),
    (
        "effect_v3/dispatch/reverse_dispatch/system.rs",
        include_str!("../../effect_v3/dispatch/reverse_dispatch/system.rs"),
    ),
    (
        "effect_v3/effects/anchor/components.rs",
        include_str!("../../effect_v3/effects/anchor/components.rs"),
    ),
    (
        "effect_v3/effects/anchor/config.rs",
        include_str!("../../effect_v3/effects/anchor/config.rs"),
    ),
    (
        "effect_v3/effects/anchor/mod.rs",
        include_str!("../../effect_v3/effects/anchor/mod.rs"),
    ),
    (
        "effect_v3/effects/anchor/systems/mod.rs",
        include_str!("../../effect_v3/effects/anchor/systems/mod.rs"),
    ),
    (
        "effect_v3/effects/anchor/systems/system.rs",
        include_str!("../../effect_v3/effects/anchor/systems/system.rs"),
    ),
    (
        "effect_v3/effects/attraction/components.rs",
        include_str!("../../effect_v3/effects/attraction/components.rs"),
    ),
    (
        "effect_v3/effects/attraction/config.rs",
        include_str!("../../effect_v3/effects/attraction/config.rs"),
    ),
    (
        "effect_v3/effects/attraction/mod.rs",
        include_str!("../../effect_v3/effects/attraction/mod.rs"),
    ),
    (
        "effect_v3/effects/attraction/systems.rs",
        include_str!("../../effect_v3/effects/attraction/systems.rs"),
    ),
    (
        "effect_v3/effects/bump_force/config.rs",
        include_str!("../../effect_v3/effects/bump_force/config.rs"),
    ),
    (
        "effect_v3/effects/bump_force/mod.rs",
        include_str!("../../effect_v3/effects/bump_force/mod.rs"),
    ),
    (
        "effect_v3/effects/chain_bolt/config.rs",
        include_str!("../../effect_v3/effects/chain_bolt/config.rs"),
    ),
    (
        "effect_v3/effects/chain_bolt/mod.rs",
        include_str!("../../effect_v3/effects/chain_bolt/mod.rs"),
    ),
    (
        "effect_v3/effects/chain_lightning/components.rs",
        include_str!("../../effect_v3/effects/chain_lightning/components.rs"),
    ),
    (
        "effect_v3/effects/chain_lightning/config/config_impl.rs",
        include_str!("../../effect_v3/effects/chain_lightning/config/config_impl.rs"),
    ),
    (
        "effect_v3/effects/chain_lightning/config/mod.rs",
        include_str!("../../effect_v3/effects/chain_lightning/config/mod.rs"),
    ),
    (
        "effect_v3/effects/chain_lightning/mod.rs",
        include_str!("../../effect_v3/effects/chain_lightning/mod.rs"),
    ),
    (
        "effect_v3/effects/chain_lightning/systems/mod.rs",
        include_str!("../../effect_v3/effects/chain_lightning/systems/mod.rs"),
    ),
    (
        "effect_v3/effects/chain_lightning/systems/system.rs",
        include_str!("../../effect_v3/effects/chain_lightning/systems/system.rs"),
    ),
    (
        "effect_v3/effects/circuit_breaker/components.rs",
        include_str!("../../effect_v3/effects/circuit_breaker/components.rs"),
    ),
    (
        "effect_v3/effects/circuit_breaker/config.rs",
        include_str!("../../effect_v3/effects/circuit_breaker/config.rs"),
    ),
    (
        "effect_v3/effects/circuit_breaker/mod.rs",
        include_str!("../../effect_v3/effects/circuit_breaker/mod.rs"),
    ),
    (
        "effect_v3/effects/circuit_breaker/systems/mod.rs",
        include_str!("../../effect_v3/effects/circuit_breaker/systems/mod.rs"),
    ),
    (
        "effect_v3/effects/circuit_breaker/systems/system.rs",
        include_str!("../../effect_v3/effects/circuit_breaker/systems/system.rs"),
    ),
    (
        "effect_v3/effects/damage_boost/config.rs",
        include_str!("../../effect_v3/effects/damage_boost/config.rs"),
    ),
    (
        "effect_v3/effects/damage_boost/mod.rs",
        include_str!("../../effect_v3/effects/damage_boost/mod.rs"),
    ),
    (
        "effect_v3/effects/die/config.rs",
        include_str!("../../effect_v3/effects/die/config.rs"),
    ),
    (
        "effect_v3/effects/die/mod.rs",
        include_str!("../../effect_v3/effects/die/mod.rs"),
    ),
    (
        "effect_v3/effects/entropy_engine/components.rs",
        include_str!("../../effect_v3/effects/entropy_engine/components.rs"),
    ),
    (
        "effect_v3/effects/entropy_engine/config.rs",
        include_str!("../../effect_v3/effects/entropy_engine/config.rs"),
    ),
    (
        "effect_v3/effects/entropy_engine/mod.rs",
        include_str!("../../effect_v3/effects/entropy_engine/mod.rs"),
    ),
    (
        "effect_v3/effects/entropy_engine/systems/mod.rs",
        include_str!("../../effect_v3/effects/entropy_engine/systems/mod.rs"),
    ),
    (
        "effect_v3/effects/entropy_engine/systems/system.rs",
        include_str!("../../effect_v3/effects/entropy_engine/systems/system.rs"),
    ),
    (
        "effect_v3/effects/explode/config.rs",
        include_str!("../../effect_v3/effects/explode/config.rs"),
    ),
    (
        "effect_v3/effects/explode/messages.rs",
        include_str!("../../effect_v3/effects/explode/messages.rs"),
    ),
    (
        "effect_v3/effects/explode/mod.rs",
        include_str!("../../effect_v3/effects/explode/mod.rs"),
    ),
    (
        "effect_v3/effects/explode/systems/apply_explode.rs",
        include_str!("../../effect_v3/effects/explode/systems/apply_explode.rs"),
    ),
    (
        "effect_v3/effects/explode/systems/mod.rs",
        include_str!("../../effect_v3/effects/explode/systems/mod.rs"),
    ),
    (
        "effect_v3/effects/flash_step/components.rs",
        include_str!("../../effect_v3/effects/flash_step/components.rs"),
    ),
    (
        "effect_v3/effects/flash_step/config.rs",
        include_str!("../../effect_v3/effects/flash_step/config.rs"),
    ),
    (
        "effect_v3/effects/flash_step/mod.rs",
        include_str!("../../effect_v3/effects/flash_step/mod.rs"),
    ),
    (
        "effect_v3/effects/gravity_well/components.rs",
        include_str!("../../effect_v3/effects/gravity_well/components.rs"),
    ),
    (
        "effect_v3/effects/gravity_well/config.rs",
        include_str!("../../effect_v3/effects/gravity_well/config.rs"),
    ),
    (
        "effect_v3/effects/gravity_well/mod.rs",
        include_str!("../../effect_v3/effects/gravity_well/mod.rs"),
    ),
    (
        "effect_v3/effects/gravity_well/systems.rs",
        include_str!("../../effect_v3/effects/gravity_well/systems.rs"),
    ),
    (
        "effect_v3/effects/lose_life/config.rs",
        include_str!("../../effect_v3/effects/lose_life/config.rs"),
    ),
    (
        "effect_v3/effects/lose_life/mod.rs",
        include_str!("../../effect_v3/effects/lose_life/mod.rs"),
    ),
    (
        "effect_v3/effects/mirror_protocol/config.rs",
        include_str!("../../effect_v3/effects/mirror_protocol/config.rs"),
    ),
    (
        "effect_v3/effects/mirror_protocol/mod.rs",
        include_str!("../../effect_v3/effects/mirror_protocol/mod.rs"),
    ),
    (
        "effect_v3/effects/mod.rs",
        include_str!("../../effect_v3/effects/mod.rs"),
    ),
    (
        "effect_v3/effects/phantom_bolt/config/config_impl.rs",
        include_str!("../../effect_v3/effects/phantom_bolt/config/config_impl.rs"),
    ),
    (
        "effect_v3/effects/phantom_bolt/config/mod.rs",
        include_str!("../../effect_v3/effects/phantom_bolt/config/mod.rs"),
    ),
    (
        "effect_v3/effects/phantom_bolt/mod.rs",
        include_str!("../../effect_v3/effects/phantom_bolt/mod.rs"),
    ),
    (
        "effect_v3/effects/piercing_beam/config/config_impl.rs",
        include_str!("../../effect_v3/effects/piercing_beam/config/config_impl.rs"),
    ),
    (
        "effect_v3/effects/piercing_beam/config/mod.rs",
        include_str!("../../effect_v3/effects/piercing_beam/config/mod.rs"),
    ),
    (
        "effect_v3/effects/piercing_beam/messages.rs",
        include_str!("../../effect_v3/effects/piercing_beam/messages.rs"),
    ),
    (
        "effect_v3/effects/piercing_beam/mod.rs",
        include_str!("../../effect_v3/effects/piercing_beam/mod.rs"),
    ),
    (
        "effect_v3/effects/piercing_beam/systems/apply_piercing_beam.rs",
        include_str!("../../effect_v3/effects/piercing_beam/systems/apply_piercing_beam.rs"),
    ),
    (
        "effect_v3/effects/piercing_beam/systems/mod.rs",
        include_str!("../../effect_v3/effects/piercing_beam/systems/mod.rs"),
    ),
    (
        "effect_v3/effects/piercing/components.rs",
        include_str!("../../effect_v3/effects/piercing/components.rs"),
    ),
    (
        "effect_v3/effects/piercing/config.rs",
        include_str!("../../effect_v3/effects/piercing/config.rs"),
    ),
    (
        "effect_v3/effects/piercing/mod.rs",
        include_str!("../../effect_v3/effects/piercing/mod.rs"),
    ),
    (
        "effect_v3/effects/pulse/components.rs",
        include_str!("../../effect_v3/effects/pulse/components.rs"),
    ),
    (
        "effect_v3/effects/pulse/config/config_impl.rs",
        include_str!("../../effect_v3/effects/pulse/config/config_impl.rs"),
    ),
    (
        "effect_v3/effects/pulse/config/mod.rs",
        include_str!("../../effect_v3/effects/pulse/config/mod.rs"),
    ),
    (
        "effect_v3/effects/pulse/mod.rs",
        include_str!("../../effect_v3/effects/pulse/mod.rs"),
    ),
    (
        "effect_v3/effects/pulse/systems/mod.rs",
        include_str!("../../effect_v3/effects/pulse/systems/mod.rs"),
    ),
    (
        "effect_v3/effects/pulse/systems/system.rs",
        include_str!("../../effect_v3/effects/pulse/systems/system.rs"),
    ),
    (
        "effect_v3/effects/quick_stop/config.rs",
        include_str!("../../effect_v3/effects/quick_stop/config.rs"),
    ),
    (
        "effect_v3/effects/quick_stop/mod.rs",
        include_str!("../../effect_v3/effects/quick_stop/mod.rs"),
    ),
    (
        "effect_v3/effects/ramping_damage/components.rs",
        include_str!("../../effect_v3/effects/ramping_damage/components.rs"),
    ),
    (
        "effect_v3/effects/ramping_damage/config/config_impl.rs",
        include_str!("../../effect_v3/effects/ramping_damage/config/config_impl.rs"),
    ),
    (
        "effect_v3/effects/ramping_damage/config/mod.rs",
        include_str!("../../effect_v3/effects/ramping_damage/config/mod.rs"),
    ),
    (
        "effect_v3/effects/ramping_damage/mod.rs",
        include_str!("../../effect_v3/effects/ramping_damage/mod.rs"),
    ),
    (
        "effect_v3/effects/ramping_damage/systems.rs",
        include_str!("../../effect_v3/effects/ramping_damage/systems.rs"),
    ),
    (
        "effect_v3/effects/random_effect/config.rs",
        include_str!("../../effect_v3/effects/random_effect/config.rs"),
    ),
    (
        "effect_v3/effects/random_effect/mod.rs",
        include_str!("../../effect_v3/effects/random_effect/mod.rs"),
    ),
    (
        "effect_v3/effects/second_wind/components.rs",
        include_str!("../../effect_v3/effects/second_wind/components.rs"),
    ),
    (
        "effect_v3/effects/second_wind/config/config_impl.rs",
        include_str!("../../effect_v3/effects/second_wind/config/config_impl.rs"),
    ),
    (
        "effect_v3/effects/second_wind/config/mod.rs",
        include_str!("../../effect_v3/effects/second_wind/config/mod.rs"),
    ),
    (
        "effect_v3/effects/second_wind/mod.rs",
        include_str!("../../effect_v3/effects/second_wind/mod.rs"),
    ),
    (
        "effect_v3/effects/second_wind/systems/mod.rs",
        include_str!("../../effect_v3/effects/second_wind/systems/mod.rs"),
    ),
    (
        "effect_v3/effects/second_wind/systems/system.rs",
        include_str!("../../effect_v3/effects/second_wind/systems/system.rs"),
    ),
    (
        "effect_v3/effects/shield/components.rs",
        include_str!("../../effect_v3/effects/shield/components.rs"),
    ),
    (
        "effect_v3/effects/shield/config/config_impl.rs",
        include_str!("../../effect_v3/effects/shield/config/config_impl.rs"),
    ),
    (
        "effect_v3/effects/shield/config/mod.rs",
        include_str!("../../effect_v3/effects/shield/config/mod.rs"),
    ),
    (
        "effect_v3/effects/shield/mod.rs",
        include_str!("../../effect_v3/effects/shield/mod.rs"),
    ),
    (
        "effect_v3/effects/shield/systems.rs",
        include_str!("../../effect_v3/effects/shield/systems.rs"),
    ),
    (
        "effect_v3/effects/shockwave/components.rs",
        include_str!("../../effect_v3/effects/shockwave/components.rs"),
    ),
    (
        "effect_v3/effects/shockwave/config.rs",
        include_str!("../../effect_v3/effects/shockwave/config.rs"),
    ),
    (
        "effect_v3/effects/shockwave/mod.rs",
        include_str!("../../effect_v3/effects/shockwave/mod.rs"),
    ),
    (
        "effect_v3/effects/shockwave/systems/mod.rs",
        include_str!("../../effect_v3/effects/shockwave/systems/mod.rs"),
    ),
    (
        "effect_v3/effects/shockwave/systems/system.rs",
        include_str!("../../effect_v3/effects/shockwave/systems/system.rs"),
    ),
    (
        "effect_v3/effects/size_boost/config.rs",
        include_str!("../../effect_v3/effects/size_boost/config.rs"),
    ),
    (
        "effect_v3/effects/size_boost/mod.rs",
        include_str!("../../effect_v3/effects/size_boost/mod.rs"),
    ),
    (
        "effect_v3/effects/spawn_bolts/config/config_impl.rs",
        include_str!("../../effect_v3/effects/spawn_bolts/config/config_impl.rs"),
    ),
    (
        "effect_v3/effects/spawn_bolts/config/mod.rs",
        include_str!("../../effect_v3/effects/spawn_bolts/config/mod.rs"),
    ),
    (
        "effect_v3/effects/spawn_bolts/mod.rs",
        include_str!("../../effect_v3/effects/spawn_bolts/mod.rs"),
    ),
    (
        "effect_v3/effects/speed_boost/config.rs",
        include_str!("../../effect_v3/effects/speed_boost/config.rs"),
    ),
    (
        "effect_v3/effects/speed_boost/mod.rs",
        include_str!("../../effect_v3/effects/speed_boost/mod.rs"),
    ),
    (
        "effect_v3/effects/tether_beam/components.rs",
        include_str!("../../effect_v3/effects/tether_beam/components.rs"),
    ),
    (
        "effect_v3/effects/tether_beam/config/config_impl.rs",
        include_str!("../../effect_v3/effects/tether_beam/config/config_impl.rs"),
    ),
    (
        "effect_v3/effects/tether_beam/config/mod.rs",
        include_str!("../../effect_v3/effects/tether_beam/config/mod.rs"),
    ),
    (
        "effect_v3/effects/tether_beam/mod.rs",
        include_str!("../../effect_v3/effects/tether_beam/mod.rs"),
    ),
    (
        "effect_v3/effects/tether_beam/systems/mod.rs",
        include_str!("../../effect_v3/effects/tether_beam/systems/mod.rs"),
    ),
    (
        "effect_v3/effects/tether_beam/systems/system.rs",
        include_str!("../../effect_v3/effects/tether_beam/systems/system.rs"),
    ),
    (
        "effect_v3/effects/time_penalty/config.rs",
        include_str!("../../effect_v3/effects/time_penalty/config.rs"),
    ),
    (
        "effect_v3/effects/time_penalty/mod.rs",
        include_str!("../../effect_v3/effects/time_penalty/mod.rs"),
    ),
    (
        "effect_v3/effects/vulnerable/config.rs",
        include_str!("../../effect_v3/effects/vulnerable/config.rs"),
    ),
    (
        "effect_v3/effects/vulnerable/mod.rs",
        include_str!("../../effect_v3/effects/vulnerable/mod.rs"),
    ),
    ("effect_v3/mod.rs", include_str!("../../effect_v3/mod.rs")),
    (
        "effect_v3/plugin.rs",
        include_str!("../../effect_v3/plugin.rs"),
    ),
    ("effect_v3/sets.rs", include_str!("../../effect_v3/sets.rs")),
    (
        "effect_v3/stacking/effect_stack/component.rs",
        include_str!("../../effect_v3/stacking/effect_stack/component.rs"),
    ),
    (
        "effect_v3/stacking/effect_stack/mod.rs",
        include_str!("../../effect_v3/stacking/effect_stack/mod.rs"),
    ),
    (
        "effect_v3/stacking/mod.rs",
        include_str!("../../effect_v3/stacking/mod.rs"),
    ),
    (
        "effect_v3/storage/armed_fired_participants.rs",
        include_str!("../../effect_v3/storage/armed_fired_participants.rs"),
    ),
    (
        "effect_v3/storage/bound_effects.rs",
        include_str!("../../effect_v3/storage/bound_effects.rs"),
    ),
    (
        "effect_v3/storage/mod.rs",
        include_str!("../../effect_v3/storage/mod.rs"),
    ),
    (
        "effect_v3/storage/spawn_stamp_registry/mod.rs",
        include_str!("../../effect_v3/storage/spawn_stamp_registry/mod.rs"),
    ),
    (
        "effect_v3/storage/spawn_stamp_registry/resource.rs",
        include_str!("../../effect_v3/storage/spawn_stamp_registry/resource.rs"),
    ),
    (
        "effect_v3/storage/spawn_stamp_registry/watchers/mod.rs",
        include_str!("../../effect_v3/storage/spawn_stamp_registry/watchers/mod.rs"),
    ),
    (
        "effect_v3/storage/spawn_stamp_registry/watchers/stamp_spawned_bolts.rs",
        include_str!(
            "../../effect_v3/storage/spawn_stamp_registry/watchers/stamp_spawned_bolts.rs"
        ),
    ),
    (
        "effect_v3/storage/spawn_stamp_registry/watchers/stamp_spawned_breakers.rs",
        include_str!(
            "../../effect_v3/storage/spawn_stamp_registry/watchers/stamp_spawned_breakers.rs"
        ),
    ),
    (
        "effect_v3/storage/spawn_stamp_registry/watchers/stamp_spawned_cells.rs",
        include_str!(
            "../../effect_v3/storage/spawn_stamp_registry/watchers/stamp_spawned_cells.rs"
        ),
    ),
    (
        "effect_v3/storage/spawn_stamp_registry/watchers/stamp_spawned_walls.rs",
        include_str!(
            "../../effect_v3/storage/spawn_stamp_registry/watchers/stamp_spawned_walls.rs"
        ),
    ),
    (
        "effect_v3/storage/staged_effects.rs",
        include_str!("../../effect_v3/storage/staged_effects.rs"),
    ),
    (
        "effect_v3/traits/fireable.rs",
        include_str!("../../effect_v3/traits/fireable.rs"),
    ),
    (
        "effect_v3/traits/mod.rs",
        include_str!("../../effect_v3/traits/mod.rs"),
    ),
    (
        "effect_v3/traits/passive_effect.rs",
        include_str!("../../effect_v3/traits/passive_effect.rs"),
    ),
    (
        "effect_v3/traits/reversible.rs",
        include_str!("../../effect_v3/traits/reversible.rs"),
    ),
    (
        "effect_v3/triggers/bolt_lost/bridges/mod.rs",
        include_str!("../../effect_v3/triggers/bolt_lost/bridges/mod.rs"),
    ),
    (
        "effect_v3/triggers/bolt_lost/bridges/system.rs",
        include_str!("../../effect_v3/triggers/bolt_lost/bridges/system.rs"),
    ),
    (
        "effect_v3/triggers/bolt_lost/mod.rs",
        include_str!("../../effect_v3/triggers/bolt_lost/mod.rs"),
    ),
    (
        "effect_v3/triggers/bolt_lost/register.rs",
        include_str!("../../effect_v3/triggers/bolt_lost/register.rs"),
    ),
    (
        "effect_v3/triggers/bump/bridges/mod.rs",
        include_str!("../../effect_v3/triggers/bump/bridges/mod.rs"),
    ),
    (
        "effect_v3/triggers/bump/bridges/system.rs",
        include_str!("../../effect_v3/triggers/bump/bridges/system.rs"),
    ),
    (
        "effect_v3/triggers/bump/mod.rs",
        include_str!("../../effect_v3/triggers/bump/mod.rs"),
    ),
    (
        "effect_v3/triggers/bump/register.rs",
        include_str!("../../effect_v3/triggers/bump/register.rs"),
    ),
    (
        "effect_v3/triggers/death/bridges/mod.rs",
        include_str!("../../effect_v3/triggers/death/bridges/mod.rs"),
    ),
    (
        "effect_v3/triggers/death/bridges/system.rs",
        include_str!("../../effect_v3/triggers/death/bridges/system.rs"),
    ),
    (
        "effect_v3/triggers/death/mod.rs",
        include_str!("../../effect_v3/triggers/death/mod.rs"),
    ),
    (
        "effect_v3/triggers/death/register.rs",
        include_str!("../../effect_v3/triggers/death/register.rs"),
    ),
    (
        "effect_v3/triggers/impact/bridges/mod.rs",
        include_str!("../../effect_v3/triggers/impact/bridges/mod.rs"),
    ),
    (
        "effect_v3/triggers/impact/bridges/system.rs",
        include_str!("../../effect_v3/triggers/impact/bridges/system.rs"),
    ),
    (
        "effect_v3/triggers/impact/mod.rs",
        include_str!("../../effect_v3/triggers/impact/mod.rs"),
    ),
    (
        "effect_v3/triggers/impact/register.rs",
        include_str!("../../effect_v3/triggers/impact/register.rs"),
    ),
    (
        "effect_v3/triggers/mod.rs",
        include_str!("../../effect_v3/triggers/mod.rs"),
    ),
    (
        "effect_v3/triggers/node/bridges/mod.rs",
        include_str!("../../effect_v3/triggers/node/bridges/mod.rs"),
    ),
    (
        "effect_v3/triggers/node/bridges/system.rs",
        include_str!("../../effect_v3/triggers/node/bridges/system.rs"),
    ),
    (
        "effect_v3/triggers/node/check_thresholds.rs",
        include_str!("../../effect_v3/triggers/node/check_thresholds.rs"),
    ),
    (
        "effect_v3/triggers/node/messages.rs",
        include_str!("../../effect_v3/triggers/node/messages.rs"),
    ),
    (
        "effect_v3/triggers/node/mod.rs",
        include_str!("../../effect_v3/triggers/node/mod.rs"),
    ),
    (
        "effect_v3/triggers/node/register.rs",
        include_str!("../../effect_v3/triggers/node/register.rs"),
    ),
    (
        "effect_v3/triggers/node/reset_fired.rs",
        include_str!("../../effect_v3/triggers/node/reset_fired.rs"),
    ),
    (
        "effect_v3/triggers/node/resources.rs",
        include_str!("../../effect_v3/triggers/node/resources.rs"),
    ),
    (
        "effect_v3/triggers/node/scan_thresholds/mod.rs",
        include_str!("../../effect_v3/triggers/node/scan_thresholds/mod.rs"),
    ),
    (
        "effect_v3/triggers/node/scan_thresholds/system.rs",
        include_str!("../../effect_v3/triggers/node/scan_thresholds/system.rs"),
    ),
    (
        "effect_v3/triggers/time/bridges/mod.rs",
        include_str!("../../effect_v3/triggers/time/bridges/mod.rs"),
    ),
    (
        "effect_v3/triggers/time/bridges/system.rs",
        include_str!("../../effect_v3/triggers/time/bridges/system.rs"),
    ),
    (
        "effect_v3/triggers/time/components.rs",
        include_str!("../../effect_v3/triggers/time/components.rs"),
    ),
    (
        "effect_v3/triggers/time/messages.rs",
        include_str!("../../effect_v3/triggers/time/messages.rs"),
    ),
    (
        "effect_v3/triggers/time/mod.rs",
        include_str!("../../effect_v3/triggers/time/mod.rs"),
    ),
    (
        "effect_v3/triggers/time/register.rs",
        include_str!("../../effect_v3/triggers/time/register.rs"),
    ),
    (
        "effect_v3/triggers/time/tick_timers/mod.rs",
        include_str!("../../effect_v3/triggers/time/tick_timers/mod.rs"),
    ),
    (
        "effect_v3/triggers/time/tick_timers/system.rs",
        include_str!("../../effect_v3/triggers/time/tick_timers/system.rs"),
    ),
    (
        "effect_v3/types/attraction_type.rs",
        include_str!("../../effect_v3/types/attraction_type.rs"),
    ),
    (
        "effect_v3/types/bump_status.rs",
        include_str!("../../effect_v3/types/bump_status.rs"),
    ),
    (
        "effect_v3/types/condition.rs",
        include_str!("../../effect_v3/types/condition.rs"),
    ),
    (
        "effect_v3/types/effect_type.rs",
        include_str!("../../effect_v3/types/effect_type.rs"),
    ),
    (
        "effect_v3/types/entity_kind.rs",
        include_str!("../../effect_v3/types/entity_kind.rs"),
    ),
    (
        "effect_v3/types/mod.rs",
        include_str!("../../effect_v3/types/mod.rs"),
    ),
    (
        "effect_v3/types/participants.rs",
        include_str!("../../effect_v3/types/participants.rs"),
    ),
    (
        "effect_v3/types/reversible_effect_type.rs",
        include_str!("../../effect_v3/types/reversible_effect_type.rs"),
    ),
    (
        "effect_v3/types/root_node.rs",
        include_str!("../../effect_v3/types/root_node.rs"),
    ),
    (
        "effect_v3/types/route_type.rs",
        include_str!("../../effect_v3/types/route_type.rs"),
    ),
    (
        "effect_v3/types/scoped_terminal.rs",
        include_str!("../../effect_v3/types/scoped_terminal.rs"),
    ),
    (
        "effect_v3/types/scoped_tree.rs",
        include_str!("../../effect_v3/types/scoped_tree.rs"),
    ),
    (
        "effect_v3/types/stamp_target.rs",
        include_str!("../../effect_v3/types/stamp_target.rs"),
    ),
    (
        "effect_v3/types/terminal.rs",
        include_str!("../../effect_v3/types/terminal.rs"),
    ),
    (
        "effect_v3/types/tree.rs",
        include_str!("../../effect_v3/types/tree.rs"),
    ),
    (
        "effect_v3/types/trigger_context.rs",
        include_str!("../../effect_v3/types/trigger_context.rs"),
    ),
    (
        "effect_v3/types/trigger.rs",
        include_str!("../../effect_v3/types/trigger.rs"),
    ),
    (
        "effect_v3/walking/during/mod.rs",
        include_str!("../../effect_v3/walking/during/mod.rs"),
    ),
    (
        "effect_v3/walking/during/system.rs",
        include_str!("../../effect_v3/walking/during/system.rs"),
    ),
    (
        "effect_v3/walking/fire.rs",
        include_str!("../../effect_v3/walking/fire.rs"),
    ),
    (
        "effect_v3/walking/mod.rs",
        include_str!("../../effect_v3/walking/mod.rs"),
    ),
    (
        "effect_v3/walking/on/mod.rs",
        include_str!("../../effect_v3/walking/on/mod.rs"),
    ),
    (
        "effect_v3/walking/on/system.rs",
        include_str!("../../effect_v3/walking/on/system.rs"),
    ),
    (
        "effect_v3/walking/once/mod.rs",
        include_str!("../../effect_v3/walking/once/mod.rs"),
    ),
    (
        "effect_v3/walking/once/system.rs",
        include_str!("../../effect_v3/walking/once/system.rs"),
    ),
    (
        "effect_v3/walking/sequence.rs",
        include_str!("../../effect_v3/walking/sequence.rs"),
    ),
    (
        "effect_v3/walking/until/mod.rs",
        include_str!("../../effect_v3/walking/until/mod.rs"),
    ),
    (
        "effect_v3/walking/until/system.rs",
        include_str!("../../effect_v3/walking/until/system.rs"),
    ),
    (
        "effect_v3/walking/walk_effects/mod.rs",
        include_str!("../../effect_v3/walking/walk_effects/mod.rs"),
    ),
    (
        "effect_v3/walking/walk_effects/system.rs",
        include_str!("../../effect_v3/walking/walk_effects/system.rs"),
    ),
    (
        "effect_v3/walking/when/mod.rs",
        include_str!("../../effect_v3/walking/when/mod.rs"),
    ),
    (
        "effect_v3/walking/when/system.rs",
        include_str!("../../effect_v3/walking/when/system.rs"),
    ),
    ("fx/components.rs", include_str!("../../fx/components.rs")),
    ("fx/mod.rs", include_str!("../../fx/mod.rs")),
    ("fx/plugin.rs", include_str!("../../fx/plugin.rs")),
    (
        "fx/systems/animate_fade_out.rs",
        include_str!("../../fx/systems/animate_fade_out.rs"),
    ),
    (
        "fx/systems/animate_punch_scale.rs",
        include_str!("../../fx/systems/animate_punch_scale.rs"),
    ),
    ("fx/systems/mod.rs", include_str!("../../fx/systems/mod.rs")),
    (
        "fx/systems/tick_effect_flash.rs",
        include_str!("../../fx/systems/tick_effect_flash.rs"),
    ),
    (
        "fx/systems/tick_phantom_flicker.rs",
        include_str!("../../fx/systems/tick_phantom_flicker.rs"),
    ),
    ("game/mod.rs", include_str!("../../game/mod.rs")),
    ("game/system.rs", include_str!("../../game/system.rs")),
    ("input/mod.rs", include_str!("../../input/mod.rs")),
    ("input/plugin.rs", include_str!("../../input/plugin.rs")),
    (
        "input/resources.rs",
        include_str!("../../input/resources.rs"),
    ),
    (
        "input/systems/mod.rs",
        include_str!("../../input/systems/mod.rs"),
    ),
    (
        "input/systems/read_input.rs",
        include_str!("../../input/systems/read_input.rs"),
    ),
    ("lib.rs", include_str!("../../lib.rs")),
    ("main.rs", include_str!("../../main.rs")),
    (
        "mutators/hazards/cascade/mod.rs",
        include_str!("../../mutators/hazards/cascade/mod.rs"),
    ),
    (
        "mutators/hazards/cascade/system.rs",
        include_str!("../../mutators/hazards/cascade/system.rs"),
    ),
    (
        "mutators/hazards/decay.rs",
        include_str!("../../mutators/hazards/decay.rs"),
    ),
    (
        "mutators/hazards/definition/mod.rs",
        include_str!("../../mutators/hazards/definition/mod.rs"),
    ),
    (
        "mutators/hazards/definition/types.rs",
        include_str!("../../mutators/hazards/definition/types.rs"),
    ),
    (
        "mutators/hazards/diffusion/mod.rs",
        include_str!("../../mutators/hazards/diffusion/mod.rs"),
    ),
    (
        "mutators/hazards/diffusion/system.rs",
        include_str!("../../mutators/hazards/diffusion/system.rs"),
    ),
    (
        "mutators/hazards/drift/mod.rs",
        include_str!("../../mutators/hazards/drift/mod.rs"),
    ),
    (
        "mutators/hazards/drift/system.rs",
        include_str!("../../mutators/hazards/drift/system.rs"),
    ),
    (
        "mutators/hazards/echo_cells/mod.rs",
        include_str!("../../mutators/hazards/echo_cells/mod.rs"),
    ),
    (
        "mutators/hazards/echo_cells/system.rs",
        include_str!("../../mutators/hazards/echo_cells/system.rs"),
    ),
    (
        "mutators/hazards/erosion/mod.rs",
        include_str!("../../mutators/hazards/erosion/mod.rs"),
    ),
    (
        "mutators/hazards/erosion/system.rs",
        include_str!("../../mutators/hazards/erosion/system.rs"),
    ),
    (
        "mutators/hazards/fan_out.rs",
        include_str!("../../mutators/hazards/fan_out.rs"),
    ),
    (
        "mutators/hazards/fracture/mod.rs",
        include_str!("../../mutators/hazards/fracture/mod.rs"),
    ),
    (
        "mutators/hazards/fracture/system.rs",
        include_str!("../../mutators/hazards/fracture/system.rs"),
    ),
    (
        "mutators/hazards/gravity_surge/mod.rs",
        include_str!("../../mutators/hazards/gravity_surge/mod.rs"),
    ),
    (
        "mutators/hazards/gravity_surge/system.rs",
        include_str!("../../mutators/hazards/gravity_surge/system.rs"),
    ),
    (
        "mutators/hazards/haste/mod.rs",
        include_str!("../../mutators/hazards/haste/mod.rs"),
    ),
    (
        "mutators/hazards/haste/system.rs",
        include_str!("../../mutators/hazards/haste/system.rs"),
    ),
    (
        "mutators/hazards/messages.rs",
        include_str!("../../mutators/hazards/messages.rs"),
    ),
    (
        "mutators/hazards/mod.rs",
        include_str!("../../mutators/hazards/mod.rs"),
    ),
    (
        "mutators/hazards/momentum/mod.rs",
        include_str!("../../mutators/hazards/momentum/mod.rs"),
    ),
    (
        "mutators/hazards/momentum/system.rs",
        include_str!("../../mutators/hazards/momentum/system.rs"),
    ),
    (
        "mutators/hazards/overcharge/mod.rs",
        include_str!("../../mutators/hazards/overcharge/mod.rs"),
    ),
    (
        "mutators/hazards/overcharge/system.rs",
        include_str!("../../mutators/hazards/overcharge/system.rs"),
    ),
    (
        "mutators/hazards/renewal/mod.rs",
        include_str!("../../mutators/hazards/renewal/mod.rs"),
    ),
    (
        "mutators/hazards/renewal/system.rs",
        include_str!("../../mutators/hazards/renewal/system.rs"),
    ),
    (
        "mutators/hazards/resonance/mod.rs",
        include_str!("../../mutators/hazards/resonance/mod.rs"),
    ),
    (
        "mutators/hazards/resonance/system.rs",
        include_str!("../../mutators/hazards/resonance/system.rs"),
    ),
    (
        "mutators/hazards/resources/mod.rs",
        include_str!("../../mutators/hazards/resources/mod.rs"),
    ),
    (
        "mutators/hazards/resources/types.rs",
        include_str!("../../mutators/hazards/resources/types.rs"),
    ),
    (
        "mutators/hazards/sympathy/mod.rs",
        include_str!("../../mutators/hazards/sympathy/mod.rs"),
    ),
    (
        "mutators/hazards/sympathy/system.rs",
        include_str!("../../mutators/hazards/sympathy/system.rs"),
    ),
    (
        "mutators/hazards/systems/dispatch_hazard_selection.rs",
        include_str!("../../mutators/hazards/systems/dispatch_hazard_selection.rs"),
    ),
    (
        "mutators/hazards/systems/mod.rs",
        include_str!("../../mutators/hazards/systems/mod.rs"),
    ),
    (
        "mutators/hazards/tether/mod.rs",
        include_str!("../../mutators/hazards/tether/mod.rs"),
    ),
    (
        "mutators/hazards/tether/system.rs",
        include_str!("../../mutators/hazards/tether/system.rs"),
    ),
    (
        "mutators/hazards/volatility/mod.rs",
        include_str!("../../mutators/hazards/volatility/mod.rs"),
    ),
    (
        "mutators/hazards/volatility/system.rs",
        include_str!("../../mutators/hazards/volatility/system.rs"),
    ),
    ("mutators/mod.rs", include_str!("../../mutators/mod.rs")),
    (
        "mutators/plugin/mod.rs",
        include_str!("../../mutators/plugin/mod.rs"),
    ),
    (
        "mutators/plugin/system.rs",
        include_str!("../../mutators/plugin/system.rs"),
    ),
    (
        "mutators/protocols/afterimage/mod.rs",
        include_str!("../../mutators/protocols/afterimage/mod.rs"),
    ),
    (
        "mutators/protocols/afterimage/system/activate.rs",
        include_str!("../../mutators/protocols/afterimage/system/activate.rs"),
    ),
    (
        "mutators/protocols/afterimage/system/config.rs",
        include_str!("../../mutators/protocols/afterimage/system/config.rs"),
    ),
    (
        "mutators/protocols/afterimage/system/mod.rs",
        include_str!("../../mutators/protocols/afterimage/system/mod.rs"),
    ),
    (
        "mutators/protocols/afterimage/system/spawn_phantom_bolt.rs",
        include_str!("../../mutators/protocols/afterimage/system/spawn_phantom_bolt.rs"),
    ),
    (
        "mutators/protocols/afterimage/system/spawn_phantom_breaker.rs",
        include_str!("../../mutators/protocols/afterimage/system/spawn_phantom_breaker.rs"),
    ),
    (
        "mutators/protocols/afterimage/system/wire.rs",
        include_str!("../../mutators/protocols/afterimage/system/wire.rs"),
    ),
    (
        "mutators/protocols/burnout/mod.rs",
        include_str!("../../mutators/protocols/burnout/mod.rs"),
    ),
    (
        "mutators/protocols/burnout/system/amplify.rs",
        include_str!("../../mutators/protocols/burnout/system/amplify.rs"),
    ),
    (
        "mutators/protocols/burnout/system/cleanup_node.rs",
        include_str!("../../mutators/protocols/burnout/system/cleanup_node.rs"),
    ),
    (
        "mutators/protocols/burnout/system/config.rs",
        include_str!("../../mutators/protocols/burnout/system/config.rs"),
    ),
    (
        "mutators/protocols/burnout/system/mod.rs",
        include_str!("../../mutators/protocols/burnout/system/mod.rs"),
    ),
    (
        "mutators/protocols/burnout/system/on_bump.rs",
        include_str!("../../mutators/protocols/burnout/system/on_bump.rs"),
    ),
    (
        "mutators/protocols/burnout/system/tick_speed_boost.rs",
        include_str!("../../mutators/protocols/burnout/system/tick_speed_boost.rs"),
    ),
    (
        "mutators/protocols/burnout/system/update_heat.rs",
        include_str!("../../mutators/protocols/burnout/system/update_heat.rs"),
    ),
    (
        "mutators/protocols/burnout/system/wire.rs",
        include_str!("../../mutators/protocols/burnout/system/wire.rs"),
    ),
    (
        "mutators/protocols/conductor/mod.rs",
        include_str!("../../mutators/protocols/conductor/mod.rs"),
    ),
    (
        "mutators/protocols/conductor/system.rs",
        include_str!("../../mutators/protocols/conductor/system.rs"),
    ),
    (
        "mutators/protocols/debt_collector/mod.rs",
        include_str!("../../mutators/protocols/debt_collector/mod.rs"),
    ),
    (
        "mutators/protocols/debt_collector/system.rs",
        include_str!("../../mutators/protocols/debt_collector/system.rs"),
    ),
    (
        "mutators/protocols/definition/mod.rs",
        include_str!("../../mutators/protocols/definition/mod.rs"),
    ),
    (
        "mutators/protocols/definition/types.rs",
        include_str!("../../mutators/protocols/definition/types.rs"),
    ),
    (
        "mutators/protocols/echo_strike/mod.rs",
        include_str!("../../mutators/protocols/echo_strike/mod.rs"),
    ),
    (
        "mutators/protocols/echo_strike/system.rs",
        include_str!("../../mutators/protocols/echo_strike/system.rs"),
    ),
    (
        "mutators/protocols/fan_out.rs",
        include_str!("../../mutators/protocols/fan_out.rs"),
    ),
    (
        "mutators/protocols/fission/mod.rs",
        include_str!("../../mutators/protocols/fission/mod.rs"),
    ),
    (
        "mutators/protocols/fission/system.rs",
        include_str!("../../mutators/protocols/fission/system.rs"),
    ),
    (
        "mutators/protocols/greed/mod.rs",
        include_str!("../../mutators/protocols/greed/mod.rs"),
    ),
    (
        "mutators/protocols/greed/system.rs",
        include_str!("../../mutators/protocols/greed/system.rs"),
    ),
    (
        "mutators/protocols/iron_curtain/mod.rs",
        include_str!("../../mutators/protocols/iron_curtain/mod.rs"),
    ),
    (
        "mutators/protocols/iron_curtain/system.rs",
        include_str!("../../mutators/protocols/iron_curtain/system.rs"),
    ),
    (
        "mutators/protocols/messages.rs",
        include_str!("../../mutators/protocols/messages.rs"),
    ),
    (
        "mutators/protocols/mod.rs",
        include_str!("../../mutators/protocols/mod.rs"),
    ),
    (
        "mutators/protocols/reckless_dash/mod.rs",
        include_str!("../../mutators/protocols/reckless_dash/mod.rs"),
    ),
    (
        "mutators/protocols/reckless_dash/system.rs",
        include_str!("../../mutators/protocols/reckless_dash/system.rs"),
    ),
    (
        "mutators/protocols/resources/mod.rs",
        include_str!("../../mutators/protocols/resources/mod.rs"),
    ),
    (
        "mutators/protocols/resources/types.rs",
        include_str!("../../mutators/protocols/resources/types.rs"),
    ),
    (
        "mutators/protocols/siphon/mod.rs",
        include_str!("../../mutators/protocols/siphon/mod.rs"),
    ),
    (
        "mutators/protocols/siphon/system.rs",
        include_str!("../../mutators/protocols/siphon/system.rs"),
    ),
    (
        "mutators/protocols/systems/dispatch_protocol_selection.rs",
        include_str!("../../mutators/protocols/systems/dispatch_protocol_selection.rs"),
    ),
    (
        "mutators/protocols/systems/gate.rs",
        include_str!("../../mutators/protocols/systems/gate.rs"),
    ),
    (
        "mutators/protocols/systems/generate_protocol_offering.rs",
        include_str!("../../mutators/protocols/systems/generate_protocol_offering.rs"),
    ),
    (
        "mutators/protocols/systems/mod.rs",
        include_str!("../../mutators/protocols/systems/mod.rs"),
    ),
    (
        "mutators/protocols/systems/reseed_protocol_rng.rs",
        include_str!("../../mutators/protocols/systems/reseed_protocol_rng.rs"),
    ),
    (
        "mutators/protocols/test_utils.rs",
        include_str!("../../mutators/protocols/test_utils.rs"),
    ),
    (
        "mutators/protocols/tier_regression/mod.rs",
        include_str!("../../mutators/protocols/tier_regression/mod.rs"),
    ),
    (
        "mutators/protocols/tier_regression/system.rs",
        include_str!("../../mutators/protocols/tier_regression/system.rs"),
    ),
    (
        "prelude/components.rs",
        include_str!("../../prelude/components.rs"),
    ),
    (
        "prelude/constants.rs",
        include_str!("../../prelude/constants.rs"),
    ),
    (
        "prelude/death_pipeline.rs",
        include_str!("../../prelude/death_pipeline.rs"),
    ),
    (
        "prelude/messages.rs",
        include_str!("../../prelude/messages.rs"),
    ),
    ("prelude/mod.rs", include_str!("../../prelude/mod.rs")),
    (
        "prelude/resources.rs",
        include_str!("../../prelude/resources.rs"),
    ),
    ("prelude/states.rs", include_str!("../../prelude/states.rs")),
    (
        "prelude/test_utils.rs",
        include_str!("../../prelude/test_utils.rs"),
    ),
    (
        "shared/asset_ron_parsing.rs",
        include_str!("../asset_ron_parsing.rs"),
    ),
    ("shared/birthing.rs", include_str!("../birthing.rs")),
    (
        "shared/collision_layers.rs",
        include_str!("../collision_layers.rs"),
    ),
    ("shared/color.rs", include_str!("../color.rs")),
    ("shared/components.rs", include_str!("../components.rs")),
    ("shared/draw_layer.rs", include_str!("../draw_layer.rs")),
    ("shared/mod.rs", include_str!("../mod.rs")),
    (
        "shared/phantom/components.rs",
        include_str!("../phantom/components.rs"),
    ),
    ("shared/phantom/mod.rs", include_str!("../phantom/mod.rs")),
    (
        "shared/physics/inverse_square.rs",
        include_str!("../physics/inverse_square.rs"),
    ),
    ("shared/physics/mod.rs", include_str!("../physics/mod.rs")),
    ("shared/playfield.rs", include_str!("../playfield.rs")),
    ("shared/resources.rs", include_str!("../resources.rs")),
    (
        "shared/rng/rng_types.rs",
        include_str!("../rng/rng_types.rs"),
    ),
    ("shared/size/mod.rs", include_str!("../size/mod.rs")),
    ("shared/size/types.rs", include_str!("../size/types.rs")),
    (
        "shared/source_id_ext.rs",
        include_str!("../source_id_ext.rs"),
    ),
    ("shared/validation.rs", include_str!("../validation.rs")),
    (
        "state/app/loading/components.rs",
        include_str!("../../state/app/loading/components.rs"),
    ),
    (
        "state/app/loading/mod.rs",
        include_str!("../../state/app/loading/mod.rs"),
    ),
    (
        "state/app/loading/plugin.rs",
        include_str!("../../state/app/loading/plugin.rs"),
    ),
    (
        "state/app/loading/systems/mod.rs",
        include_str!("../../state/app/loading/systems/mod.rs"),
    ),
    (
        "state/app/loading/systems/spawn_loading_screen.rs",
        include_str!("../../state/app/loading/systems/spawn_loading_screen.rs"),
    ),
    (
        "state/app/loading/systems/update_loading_bar.rs",
        include_str!("../../state/app/loading/systems/update_loading_bar.rs"),
    ),
    ("state/app/mod.rs", include_str!("../../state/app/mod.rs")),
    ("state/cleanup.rs", include_str!("../../state/cleanup.rs")),
    (
        "state/menu/main/components.rs",
        include_str!("../../state/menu/main/components.rs"),
    ),
    (
        "state/menu/main/mod.rs",
        include_str!("../../state/menu/main/mod.rs"),
    ),
    (
        "state/menu/main/plugin.rs",
        include_str!("../../state/menu/main/plugin.rs"),
    ),
    (
        "state/menu/main/resources.rs",
        include_str!("../../state/menu/main/resources.rs"),
    ),
    (
        "state/menu/main/systems/handle_main_menu_input.rs",
        include_str!("../../state/menu/main/systems/handle_main_menu_input.rs"),
    ),
    (
        "state/menu/main/systems/mod.rs",
        include_str!("../../state/menu/main/systems/mod.rs"),
    ),
    (
        "state/menu/main/systems/spawn_main_menu.rs",
        include_str!("../../state/menu/main/systems/spawn_main_menu.rs"),
    ),
    (
        "state/menu/main/systems/update_menu_colors.rs",
        include_str!("../../state/menu/main/systems/update_menu_colors.rs"),
    ),
    ("state/menu/mod.rs", include_str!("../../state/menu/mod.rs")),
    (
        "state/menu/start_game/components.rs",
        include_str!("../../state/menu/start_game/components.rs"),
    ),
    (
        "state/menu/start_game/mod.rs",
        include_str!("../../state/menu/start_game/mod.rs"),
    ),
    (
        "state/menu/start_game/plugin.rs",
        include_str!("../../state/menu/start_game/plugin.rs"),
    ),
    (
        "state/menu/start_game/resources.rs",
        include_str!("../../state/menu/start_game/resources.rs"),
    ),
    (
        "state/menu/start_game/systems/handle_run_setup_input.rs",
        include_str!("../../state/menu/start_game/systems/handle_run_setup_input.rs"),
    ),
    (
        "state/menu/start_game/systems/handle_seed_input.rs",
        include_str!("../../state/menu/start_game/systems/handle_seed_input.rs"),
    ),
    (
        "state/menu/start_game/systems/mod.rs",
        include_str!("../../state/menu/start_game/systems/mod.rs"),
    ),
    (
        "state/menu/start_game/systems/spawn_run_setup.rs",
        include_str!("../../state/menu/start_game/systems/spawn_run_setup.rs"),
    ),
    (
        "state/menu/start_game/systems/update_run_setup_colors.rs",
        include_str!("../../state/menu/start_game/systems/update_run_setup_colors.rs"),
    ),
    (
        "state/menu/start_game/systems/update_seed_display.rs",
        include_str!("../../state/menu/start_game/systems/update_seed_display.rs"),
    ),
    ("state/menu/mod.rs", include_str!("../../state/menu/mod.rs")),
    (
        "state/pause/components.rs",
        include_str!("../../state/pause/components.rs"),
    ),
    (
        "state/pause/mod.rs",
        include_str!("../../state/pause/mod.rs"),
    ),
    (
        "state/pause/plugin.rs",
        include_str!("../../state/pause/plugin.rs"),
    ),
    (
        "state/pause/resources.rs",
        include_str!("../../state/pause/resources.rs"),
    ),
    (
        "state/pause/systems/handle_pause_input.rs",
        include_str!("../../state/pause/systems/handle_pause_input.rs"),
    ),
    (
        "state/pause/systems/mod.rs",
        include_str!("../../state/pause/systems/mod.rs"),
    ),
    (
        "state/pause/systems/spawn_pause_menu.rs",
        include_str!("../../state/pause/systems/spawn_pause_menu.rs"),
    ),
    (
        "state/pause/systems/toggle_pause.rs",
        include_str!("../../state/pause/systems/toggle_pause.rs"),
    ),
    (
        "state/pause/systems/update_pause_menu_colors.rs",
        include_str!("../../state/pause/systems/update_pause_menu_colors.rs"),
    ),
    (
        "state/plugin/mod.rs",
        include_str!("../../state/plugin/mod.rs"),
    ),
    (
        "state/plugin/system.rs",
        include_str!("../../state/plugin/system.rs"),
    ),
    (
        "state/run/chip_select/components.rs",
        include_str!("../../state/run/chip_select/components.rs"),
    ),
    (
        "state/run/chip_select/messages.rs",
        include_str!("../../state/run/chip_select/messages.rs"),
    ),
    (
        "state/run/chip_select/mod.rs",
        include_str!("../../state/run/chip_select/mod.rs"),
    ),
    (
        "state/run/chip_select/plugin.rs",
        include_str!("../../state/run/chip_select/plugin.rs"),
    ),
    (
        "state/run/chip_select/resources.rs",
        include_str!("../../state/run/chip_select/resources.rs"),
    ),
    (
        "state/run/chip_select/sets.rs",
        include_str!("../../state/run/chip_select/sets.rs"),
    ),
    (
        "state/run/chip_select/systems/detect_first_evolution.rs",
        include_str!("../../state/run/chip_select/systems/detect_first_evolution.rs"),
    ),
    (
        "state/run/chip_select/systems/generate_chip_offerings.rs",
        include_str!("../../state/run/chip_select/systems/generate_chip_offerings.rs"),
    ),
    (
        "state/run/chip_select/systems/handle_chip_input.rs",
        include_str!("../../state/run/chip_select/systems/handle_chip_input.rs"),
    ),
    (
        "state/run/chip_select/systems/mod.rs",
        include_str!("../../state/run/chip_select/systems/mod.rs"),
    ),
    (
        "state/run/chip_select/systems/reseed_chip_rng/mod.rs",
        include_str!("../../state/run/chip_select/systems/reseed_chip_rng/mod.rs"),
    ),
    (
        "state/run/chip_select/systems/reseed_chip_rng/system.rs",
        include_str!("../../state/run/chip_select/systems/reseed_chip_rng/system.rs"),
    ),
    (
        "state/run/chip_select/systems/snapshot_node_highlights/mod.rs",
        include_str!("../../state/run/chip_select/systems/snapshot_node_highlights/mod.rs"),
    ),
    (
        "state/run/chip_select/systems/snapshot_node_highlights/system.rs",
        include_str!("../../state/run/chip_select/systems/snapshot_node_highlights/system.rs"),
    ),
    (
        "state/run/chip_select/systems/spawn_chip_select/mod.rs",
        include_str!("../../state/run/chip_select/systems/spawn_chip_select/mod.rs"),
    ),
    (
        "state/run/chip_select/systems/spawn_chip_select/system.rs",
        include_str!("../../state/run/chip_select/systems/spawn_chip_select/system.rs"),
    ),
    (
        "state/run/chip_select/systems/tick_chip_select_count.rs",
        include_str!("../../state/run/chip_select/systems/tick_chip_select_count.rs"),
    ),
    (
        "state/run/chip_select/systems/tick_chip_timer.rs",
        include_str!("../../state/run/chip_select/systems/tick_chip_timer.rs"),
    ),
    (
        "state/run/chip_select/systems/track_chips_collected.rs",
        include_str!("../../state/run/chip_select/systems/track_chips_collected.rs"),
    ),
    (
        "state/run/chip_select/systems/update_chip_display.rs",
        include_str!("../../state/run/chip_select/systems/update_chip_display.rs"),
    ),
    (
        "state/run/components.rs",
        include_str!("../../state/run/components.rs"),
    ),
    (
        "state/run/definition/mod.rs",
        include_str!("../../state/run/definition/mod.rs"),
    ),
    (
        "state/run/definition/types.rs",
        include_str!("../../state/run/definition/types.rs"),
    ),
    (
        "state/run/hazard_select/components.rs",
        include_str!("../../state/run/hazard_select/components.rs"),
    ),
    (
        "state/run/hazard_select/mod.rs",
        include_str!("../../state/run/hazard_select/mod.rs"),
    ),
    (
        "state/run/hazard_select/plugin.rs",
        include_str!("../../state/run/hazard_select/plugin.rs"),
    ),
    (
        "state/run/hazard_select/resources.rs",
        include_str!("../../state/run/hazard_select/resources.rs"),
    ),
    (
        "state/run/hazard_select/sets.rs",
        include_str!("../../state/run/hazard_select/sets.rs"),
    ),
    (
        "state/run/hazard_select/systems/generate_hazard_offerings.rs",
        include_str!("../../state/run/hazard_select/systems/generate_hazard_offerings.rs"),
    ),
    (
        "state/run/hazard_select/systems/handle_hazard_input.rs",
        include_str!("../../state/run/hazard_select/systems/handle_hazard_input.rs"),
    ),
    (
        "state/run/hazard_select/systems/mod.rs",
        include_str!("../../state/run/hazard_select/systems/mod.rs"),
    ),
    (
        "state/run/hazard_select/systems/reseed_hazard_rng/mod.rs",
        include_str!("../../state/run/hazard_select/systems/reseed_hazard_rng/mod.rs"),
    ),
    (
        "state/run/hazard_select/systems/reseed_hazard_rng/system.rs",
        include_str!("../../state/run/hazard_select/systems/reseed_hazard_rng/system.rs"),
    ),
    (
        "state/run/hazard_select/systems/spawn_hazard_select.rs",
        include_str!("../../state/run/hazard_select/systems/spawn_hazard_select.rs"),
    ),
    (
        "state/run/hazard_select/systems/tick_hazard_timer.rs",
        include_str!("../../state/run/hazard_select/systems/tick_hazard_timer.rs"),
    ),
    (
        "state/run/hazard_select/systems/update_hazard_display.rs",
        include_str!("../../state/run/hazard_select/systems/update_hazard_display.rs"),
    ),
    (
        "state/run/loading/mod.rs",
        include_str!("../../state/run/loading/mod.rs"),
    ),
    (
        "state/run/loading/systems/capture_run_seed.rs",
        include_str!("../../state/run/loading/systems/capture_run_seed.rs"),
    ),
    (
        "state/run/loading/systems/generate_node_sequence/mod.rs",
        include_str!("../../state/run/loading/systems/generate_node_sequence/mod.rs"),
    ),
    (
        "state/run/loading/systems/generate_node_sequence/system.rs",
        include_str!("../../state/run/loading/systems/generate_node_sequence/system.rs"),
    ),
    (
        "state/run/loading/systems/mod.rs",
        include_str!("../../state/run/loading/systems/mod.rs"),
    ),
    (
        "state/run/loading/systems/reset_run_state/mod.rs",
        include_str!("../../state/run/loading/systems/reset_run_state/mod.rs"),
    ),
    (
        "state/run/loading/systems/reset_run_state/system.rs",
        include_str!("../../state/run/loading/systems/reset_run_state/system.rs"),
    ),
    (
        "state/run/messages.rs",
        include_str!("../../state/run/messages.rs"),
    ),
    ("state/run/mod.rs", include_str!("../../state/run/mod.rs")),
    (
        "state/run/node/definition/mod.rs",
        include_str!("../../state/run/node/definition/mod.rs"),
    ),
    (
        "state/run/node/definition/types.rs",
        include_str!("../../state/run/node/definition/types.rs"),
    ),
    (
        "state/run/node/highlights/mod.rs",
        include_str!("../../state/run/node/highlights/mod.rs"),
    ),
    (
        "state/run/node/highlights/systems/detect_close_save.rs",
        include_str!("../../state/run/node/highlights/systems/detect_close_save.rs"),
    ),
    (
        "state/run/node/highlights/systems/detect_combo_king.rs",
        include_str!("../../state/run/node/highlights/systems/detect_combo_king.rs"),
    ),
    (
        "state/run/node/highlights/systems/detect_mass_destruction.rs",
        include_str!("../../state/run/node/highlights/systems/detect_mass_destruction.rs"),
    ),
    (
        "state/run/node/highlights/systems/detect_nail_biter.rs",
        include_str!("../../state/run/node/highlights/systems/detect_nail_biter.rs"),
    ),
    (
        "state/run/node/highlights/systems/detect_pinball_wizard.rs",
        include_str!("../../state/run/node/highlights/systems/detect_pinball_wizard.rs"),
    ),
    (
        "state/run/node/highlights/systems/mod.rs",
        include_str!("../../state/run/node/highlights/systems/mod.rs"),
    ),
    (
        "state/run/node/hud/components.rs",
        include_str!("../../state/run/node/hud/components.rs"),
    ),
    (
        "state/run/node/hud/mod.rs",
        include_str!("../../state/run/node/hud/mod.rs"),
    ),
    (
        "state/run/node/hud/resources.rs",
        include_str!("../../state/run/node/hud/resources.rs"),
    ),
    (
        "state/run/node/hud/sets.rs",
        include_str!("../../state/run/node/hud/sets.rs"),
    ),
    (
        "state/run/node/hud/systems/mod.rs",
        include_str!("../../state/run/node/hud/systems/mod.rs"),
    ),
    (
        "state/run/node/hud/systems/spawn_side_panels.rs",
        include_str!("../../state/run/node/hud/systems/spawn_side_panels.rs"),
    ),
    (
        "state/run/node/hud/systems/spawn_timer_hud.rs",
        include_str!("../../state/run/node/hud/systems/spawn_timer_hud.rs"),
    ),
    (
        "state/run/node/hud/systems/update_timer_display.rs",
        include_str!("../../state/run/node/hud/systems/update_timer_display.rs"),
    ),
    (
        "state/run/node/lifecycle/mod.rs",
        include_str!("../../state/run/node/lifecycle/mod.rs"),
    ),
    (
        "state/run/node/lifecycle/systems/handle_breaker_death.rs",
        include_str!("../../state/run/node/lifecycle/systems/handle_breaker_death.rs"),
    ),
    (
        "state/run/node/lifecycle/systems/handle_node_cleared.rs",
        include_str!("../../state/run/node/lifecycle/systems/handle_node_cleared.rs"),
    ),
    (
        "state/run/node/lifecycle/systems/handle_run_lost.rs",
        include_str!("../../state/run/node/lifecycle/systems/handle_run_lost.rs"),
    ),
    (
        "state/run/node/lifecycle/systems/handle_timer_expired.rs",
        include_str!("../../state/run/node/lifecycle/systems/handle_timer_expired.rs"),
    ),
    (
        "state/run/node/lifecycle/systems/mod.rs",
        include_str!("../../state/run/node/lifecycle/systems/mod.rs"),
    ),
    (
        "state/run/node/lifecycle/systems/reset_highlight_tracker.rs",
        include_str!("../../state/run/node/lifecycle/systems/reset_highlight_tracker.rs"),
    ),
    (
        "state/run/node/lifecycle/systems/spawn_highlight_text/mod.rs",
        include_str!("../../state/run/node/lifecycle/systems/spawn_highlight_text/mod.rs"),
    ),
    (
        "state/run/node/lifecycle/systems/spawn_highlight_text/system.rs",
        include_str!("../../state/run/node/lifecycle/systems/spawn_highlight_text/system.rs"),
    ),
    (
        "state/run/node/messages.rs",
        include_str!("../../state/run/node/messages.rs"),
    ),
    (
        "state/run/node/mod.rs",
        include_str!("../../state/run/node/mod.rs"),
    ),
    (
        "state/run/node/plugin.rs",
        include_str!("../../state/run/node/plugin.rs"),
    ),
    (
        "state/run/node/resources/definitions.rs",
        include_str!("../../state/run/node/resources/definitions.rs"),
    ),
    (
        "state/run/node/resources/mod.rs",
        include_str!("../../state/run/node/resources/mod.rs"),
    ),
    (
        "state/run/node/sets.rs",
        include_str!("../../state/run/node/sets.rs"),
    ),
    (
        "state/run/node/systems/all_animate_in_complete.rs",
        include_str!("../../state/run/node/systems/all_animate_in_complete.rs"),
    ),
    (
        "state/run/node/systems/apply_increase_node_timer.rs",
        include_str!("../../state/run/node/systems/apply_increase_node_timer.rs"),
    ),
    (
        "state/run/node/systems/apply_node_scale_to_bolt.rs",
        include_str!("../../state/run/node/systems/apply_node_scale_to_bolt.rs"),
    ),
    (
        "state/run/node/systems/apply_node_scale_to_breaker.rs",
        include_str!("../../state/run/node/systems/apply_node_scale_to_breaker.rs"),
    ),
    (
        "state/run/node/systems/apply_reduce_node_timer.rs",
        include_str!("../../state/run/node/systems/apply_reduce_node_timer.rs"),
    ),
    (
        "state/run/node/systems/check_spawn_complete.rs",
        include_str!("../../state/run/node/systems/check_spawn_complete.rs"),
    ),
    (
        "state/run/node/systems/dispatch_cell_effects/mod.rs",
        include_str!("../../state/run/node/systems/dispatch_cell_effects/mod.rs"),
    ),
    (
        "state/run/node/systems/dispatch_cell_effects/system.rs",
        include_str!("../../state/run/node/systems/dispatch_cell_effects/system.rs"),
    ),
    (
        "state/run/node/systems/init_clear_remaining.rs",
        include_str!("../../state/run/node/systems/init_clear_remaining.rs"),
    ),
    (
        "state/run/node/systems/init_node_timer.rs",
        include_str!("../../state/run/node/systems/init_node_timer.rs"),
    ),
    (
        "state/run/node/systems/mod.rs",
        include_str!("../../state/run/node/systems/mod.rs"),
    ),
    (
        "state/run/node/systems/reset_bolt/mod.rs",
        include_str!("../../state/run/node/systems/reset_bolt/mod.rs"),
    ),
    (
        "state/run/node/systems/reset_bolt/system.rs",
        include_str!("../../state/run/node/systems/reset_bolt/system.rs"),
    ),
    (
        "state/run/node/systems/reset_breaker.rs",
        include_str!("../../state/run/node/systems/reset_breaker.rs"),
    ),
    (
        "state/run/node/systems/set_active_layout.rs",
        include_str!("../../state/run/node/systems/set_active_layout.rs"),
    ),
    (
        "state/run/node/systems/spawn_cells_from_layout/geometry.rs",
        include_str!("../../state/run/node/systems/spawn_cells_from_layout/geometry.rs"),
    ),
    (
        "state/run/node/systems/spawn_cells_from_layout/lock_resolution.rs",
        include_str!("../../state/run/node/systems/spawn_cells_from_layout/lock_resolution.rs"),
    ),
    (
        "state/run/node/systems/spawn_cells_from_layout/mod.rs",
        include_str!("../../state/run/node/systems/spawn_cells_from_layout/mod.rs"),
    ),
    (
        "state/run/node/systems/spawn_cells_from_layout/spawning.rs",
        include_str!("../../state/run/node/systems/spawn_cells_from_layout/spawning.rs"),
    ),
    (
        "state/run/node/systems/spawn_walls/mod.rs",
        include_str!("../../state/run/node/systems/spawn_walls/mod.rs"),
    ),
    (
        "state/run/node/systems/spawn_walls/system.rs",
        include_str!("../../state/run/node/systems/spawn_walls/system.rs"),
    ),
    (
        "state/run/node/systems/tick_node_timer.rs",
        include_str!("../../state/run/node/systems/tick_node_timer.rs"),
    ),
    (
        "state/run/node/systems/track_node_completion.rs",
        include_str!("../../state/run/node/systems/track_node_completion.rs"),
    ),
    (
        "state/run/node/tracking/mod.rs",
        include_str!("../../state/run/node/tracking/mod.rs"),
    ),
    (
        "state/run/node/tracking/systems/mod.rs",
        include_str!("../../state/run/node/tracking/systems/mod.rs"),
    ),
    (
        "state/run/node/tracking/systems/track_bolts_lost.rs",
        include_str!("../../state/run/node/tracking/systems/track_bolts_lost.rs"),
    ),
    (
        "state/run/node/tracking/systems/track_bumps.rs",
        include_str!("../../state/run/node/tracking/systems/track_bumps.rs"),
    ),
    (
        "state/run/node/tracking/systems/track_cells_destroyed.rs",
        include_str!("../../state/run/node/tracking/systems/track_cells_destroyed.rs"),
    ),
    (
        "state/run/node/tracking/systems/track_evolution_damage.rs",
        include_str!("../../state/run/node/tracking/systems/track_evolution_damage.rs"),
    ),
    (
        "state/run/node/tracking/systems/track_node_cleared_stats/mod.rs",
        include_str!("../../state/run/node/tracking/systems/track_node_cleared_stats/mod.rs"),
    ),
    (
        "state/run/node/tracking/systems/track_node_cleared_stats/system.rs",
        include_str!("../../state/run/node/tracking/systems/track_node_cleared_stats/system.rs"),
    ),
    (
        "state/run/node/tracking/systems/track_time_elapsed.rs",
        include_str!("../../state/run/node/tracking/systems/track_time_elapsed.rs"),
    ),
    (
        "state/run/plugin.rs",
        include_str!("../../state/run/plugin.rs"),
    ),
    (
        "state/run/resources/definitions.rs",
        include_str!("../../state/run/resources/definitions.rs"),
    ),
    (
        "state/run/resources/mod.rs",
        include_str!("../../state/run/resources/mod.rs"),
    ),
    (
        "state/run/run_end/components.rs",
        include_str!("../../state/run/run_end/components.rs"),
    ),
    (
        "state/run/run_end/mod.rs",
        include_str!("../../state/run/run_end/mod.rs"),
    ),
    (
        "state/run/run_end/plugin.rs",
        include_str!("../../state/run/run_end/plugin.rs"),
    ),
    (
        "state/run/run_end/systems/detect_most_powerful_evolution.rs",
        include_str!("../../state/run/run_end/systems/detect_most_powerful_evolution.rs"),
    ),
    (
        "state/run/run_end/systems/handle_run_end_input.rs",
        include_str!("../../state/run/run_end/systems/handle_run_end_input.rs"),
    ),
    (
        "state/run/run_end/systems/mod.rs",
        include_str!("../../state/run/run_end/systems/mod.rs"),
    ),
    (
        "state/run/run_end/systems/spawn_run_end_screen/mod.rs",
        include_str!("../../state/run/run_end/systems/spawn_run_end_screen/mod.rs"),
    ),
    (
        "state/run/run_end/systems/spawn_run_end_screen/system.rs",
        include_str!("../../state/run/run_end/systems/spawn_run_end_screen/system.rs"),
    ),
    (
        "state/run/systems/advance_node.rs",
        include_str!("../../state/run/systems/advance_node.rs"),
    ),
    (
        "state/run/systems/gameplay_visibility.rs",
        include_str!("../../state/run/systems/gameplay_visibility.rs"),
    ),
    (
        "state/run/systems/mod.rs",
        include_str!("../../state/run/systems/mod.rs"),
    ),
    (
        "state/run/systems/select_highlights/mod.rs",
        include_str!("../../state/run/systems/select_highlights/mod.rs"),
    ),
    (
        "state/run/systems/select_highlights/system.rs",
        include_str!("../../state/run/systems/select_highlights/system.rs"),
    ),
    (
        "state/run/systems/setup_run/mod.rs",
        include_str!("../../state/run/systems/setup_run/mod.rs"),
    ),
    (
        "state/run/systems/setup_run/system.rs",
        include_str!("../../state/run/systems/setup_run/system.rs"),
    ),
    (
        "state/transition/mod.rs",
        include_str!("../../state/transition/mod.rs"),
    ),
    (
        "state/transition/system.rs",
        include_str!("../../state/transition/system.rs"),
    ),
    (
        "state/types/app_state.rs",
        include_str!("../../state/types/app_state.rs"),
    ),
    (
        "state/types/chip_select_state.rs",
        include_str!("../../state/types/chip_select_state.rs"),
    ),
    (
        "state/types/game_state.rs",
        include_str!("../../state/types/game_state.rs"),
    ),
    (
        "state/types/hazard_select_state.rs",
        include_str!("../../state/types/hazard_select_state.rs"),
    ),
    (
        "state/types/menu_state.rs",
        include_str!("../../state/types/menu_state.rs"),
    ),
    (
        "state/types/mod.rs",
        include_str!("../../state/types/mod.rs"),
    ),
    (
        "state/types/node_state.rs",
        include_str!("../../state/types/node_state.rs"),
    ),
    (
        "state/types/run_end_state.rs",
        include_str!("../../state/types/run_end_state.rs"),
    ),
    (
        "state/types/run_state.rs",
        include_str!("../../state/types/run_state.rs"),
    ),
    (
        "walls/builder/core/mod.rs",
        include_str!("../../walls/builder/core/mod.rs"),
    ),
    (
        "walls/builder/core/terminal.rs",
        include_str!("../../walls/builder/core/terminal.rs"),
    ),
    (
        "walls/builder/core/transitions.rs",
        include_str!("../../walls/builder/core/transitions.rs"),
    ),
    (
        "walls/builder/core/types.rs",
        include_str!("../../walls/builder/core/types.rs"),
    ),
    (
        "walls/builder/mod.rs",
        include_str!("../../walls/builder/mod.rs"),
    ),
    (
        "walls/components.rs",
        include_str!("../../walls/components.rs"),
    ),
    (
        "walls/definition.rs",
        include_str!("../../walls/definition.rs"),
    ),
    ("walls/messages.rs", include_str!("../../walls/messages.rs")),
    ("walls/mod.rs", include_str!("../../walls/mod.rs")),
    ("walls/plugin.rs", include_str!("../../walls/plugin.rs")),
    (
        "walls/registry/core.rs",
        include_str!("../../walls/registry/core.rs"),
    ),
    (
        "walls/registry/mod.rs",
        include_str!("../../walls/registry/mod.rs"),
    ),
    (
        "walls/systems/mod.rs",
        include_str!("../../walls/systems/mod.rs"),
    ),
    (
        "walls/test_utils.rs",
        include_str!("../../walls/test_utils.rs"),
    ),
];
