//! Plugin and builder for the `rantzsoft_defaults` config pipeline.

use std::sync::Mutex;

use bevy::prelude::*;

/// System sets for the defaults pipeline.
#[derive(SystemSet, Debug, Clone, PartialEq, Eq, Hash)]
pub enum DefaultsSystems {
    /// Systems that seed config resources from loaded defaults assets.
    Seed,
    /// Systems that propagate modified defaults assets to config resources.
    PropagateDefaults,
}

/// Plugin that wires the config defaults pipeline.
///
/// Construct via [`RantzDefaultsPluginBuilder`].
pub struct RantzDefaultsPlugin {
    registrations: Mutex<Vec<Box<dyn FnOnce(&mut App) + Send>>>,
}

/// Builder for [`RantzDefaultsPlugin`].
///
/// Use [`register_config`](Self::register_config) to register each
/// `SeedableConfig` type, then call [`build`](Self::build) to produce the
/// plugin.
pub struct RantzDefaultsPluginBuilder {
    registrations: Vec<Box<dyn FnOnce(&mut App) + Send>>,
}

impl Default for RantzDefaultsPluginBuilder {
    fn default() -> Self {
        Self {
            registrations: Vec::new(),
        }
    }
}

impl RantzDefaultsPluginBuilder {
    /// Creates a new empty builder.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Registers a config type with the plugin.
    ///
    /// This will set up the RON asset loader, startup handle initialization,
    /// seed system, and propagate system for the given `SeedableConfig` type.
    #[must_use]
    pub fn register_config<D: crate::seedable::SeedableConfig>(mut self) -> Self {
        self.registrations.push(Box::new(|app: &mut App| {
            app.init_asset::<D>();
            app.add_systems(
                Startup,
                crate::systems::init_defaults_handle::<D>,
            );
            #[cfg(feature = "progress")]
            app.add_systems(
                Update,
                crate::systems::seed_config::<D>
                    .map(drop)
                    .in_set(DefaultsSystems::Seed),
            );
        }));
        self
    }

    /// Builds the plugin from the accumulated registrations.
    #[must_use]
    pub fn build(self) -> RantzDefaultsPlugin {
        RantzDefaultsPlugin {
            registrations: Mutex::new(self.registrations),
        }
    }
}

impl Plugin for RantzDefaultsPlugin {
    fn build(&self, app: &mut App) {
        let mut registrations = self
            .registrations
            .lock()
            .expect("defaults plugin lock poisoned");
        for registration in registrations.drain(..) {
            registration(app);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    use crate::handle::DefaultsHandle;

    /// Test config type generated by the `GameConfig` derive macro.
    #[derive(Resource, Debug, Clone, PartialEq, Default, crate::GameConfig)]
    #[game_config(
        defaults = "TestDefaults",
        path = "config/test.ron",
        ext = "test.ron"
    )]
    struct TestConfig {
        value: f32,
    }

    /// `DefaultsSystems::Seed` and `DefaultsSystems::PropagateDefaults` are
    /// distinct variants that implement `SystemSet`.
    #[test]
    fn defaults_systems_variants_are_distinct() {
        let seed = DefaultsSystems::Seed;
        let propagate = DefaultsSystems::PropagateDefaults;
        assert_ne!(
            seed, propagate,
            "Seed and PropagateDefaults should be distinct system sets"
        );
    }

    /// After adding a plugin built with `register_config`, the asset loader
    /// for the registered defaults type should be available (the plugin
    /// registers it).
    #[test]
    fn plugin_registers_asset_loader() {
        let plugin = RantzDefaultsPluginBuilder::new()
            .register_config::<TestDefaults>()
            .build();

        let mut app = App::new();
        app.add_plugins((MinimalPlugins, AssetPlugin::default()));
        app.add_plugins(plugin);

        // After the plugin is added, we should be able to get the asset
        // collection for TestDefaults (the loader registered via init_asset).
        // If the plugin properly registers the loader, the Assets<TestDefaults>
        // resource should exist.
        app.update();

        assert!(
            app.world()
                .get_resource::<Assets<TestDefaults>>()
                .is_some(),
            "Assets<TestDefaults> should be registered by the plugin"
        );
    }

    /// After startup, the plugin should insert `DefaultsHandle<TestDefaults>`.
    #[test]
    fn plugin_inserts_defaults_handle_on_startup() {
        let plugin = RantzDefaultsPluginBuilder::new()
            .register_config::<TestDefaults>()
            .build();

        let mut app = App::new();
        app.add_plugins((MinimalPlugins, AssetPlugin::default()));
        app.add_plugins(plugin);

        // Startup systems run on first update.
        app.update();

        assert!(
            app.world()
                .get_resource::<DefaultsHandle<TestDefaults>>()
                .is_some(),
            "DefaultsHandle<TestDefaults> should exist after plugin startup"
        );
    }

    /// The seed system should run during the loading phase. We verify this
    /// indirectly: after inserting a loaded asset and its handle, the config
    /// resource should be seeded after an update cycle.
    ///
    /// The test manually registers the asset type and inserts a loaded asset.
    /// The plugin should register the seed system that reads it.
    #[test]
    fn plugin_seed_system_seeds_config() {
        let plugin = RantzDefaultsPluginBuilder::new()
            .register_config::<TestDefaults>()
            .build();

        let mut app = App::new();
        app.add_plugins((MinimalPlugins, AssetPlugin::default()));
        // Manually register asset type so we can add assets for the seed
        // system. The plugin should also register it, but we need it early
        // for setup.
        app.init_asset::<TestDefaults>();
        app.add_plugins(plugin);

        // First update runs startup (inserts DefaultsHandle).
        app.update();

        // Insert a loaded asset and update the handle to point to it.
        let defaults = TestDefaults { value: 42.0 };
        let handle = {
            let mut assets =
                app.world_mut().resource_mut::<Assets<TestDefaults>>();
            assets.add(defaults)
        };
        app.world_mut()
            .insert_resource(DefaultsHandle(handle));

        // Run update to trigger seed system.
        app.update();

        let config = app
            .world()
            .get_resource::<TestConfig>()
            .expect("TestConfig should be seeded by the plugin");
        assert!(
            (config.value - 42.0).abs() < f32::EPSILON,
            "TestConfig.value should be 42.0, got {}",
            config.value
        );
    }
}
