//! Generic systems for seeding and propagating config resources from defaults
//! assets.

use bevy::prelude::*;
#[cfg(feature = "progress")]
use iyes_progress::prelude::*;

use crate::{handle::DefaultsHandle, seedable::SeedableConfig};

/// Seeds a `Config` resource from the loaded defaults asset.
///
/// Returns [`Progress`] indicating whether the config has been seeded.
/// Uses a [`Local<bool>`] to ensure idempotency — once seeded, always reports
/// done without re-inserting.
#[cfg(feature = "progress")]
pub fn seed_config<D: SeedableConfig>(
    handle: Option<Res<DefaultsHandle<D>>>,
    assets: Res<Assets<D>>,
    mut commands: Commands,
    mut seeded: Local<bool>,
) -> Progress {
    if *seeded {
        return Progress { done: 1, total: 1 };
    }
    let Some(handle) = handle else {
        return Progress { done: 0, total: 1 };
    };
    let Some(defaults) = assets.get(handle.0.id()) else {
        return Progress { done: 0, total: 1 };
    };
    commands.insert_resource::<D::Config>(defaults.clone().into());
    *seeded = true;
    Progress { done: 1, total: 1 }
}

/// Watches for [`AssetEvent::Modified`] on the defaults asset and re-seeds
/// the `Config` resource with updated values.
pub fn propagate_defaults<D: SeedableConfig>(
    mut events: MessageReader<AssetEvent<D>>,
    handle: Res<DefaultsHandle<D>>,
    assets: Res<Assets<D>>,
    mut commands: Commands,
) {
    for event in events.read() {
        if event.is_modified(handle.0.id())
            && let Some(defaults) = assets.get(handle.0.id())
        {
            commands.insert_resource::<D::Config>(defaults.clone().into());
        }
    }
}

/// Startup system that loads the defaults asset and inserts a
/// [`DefaultsHandle`] resource.
pub fn init_defaults_handle<D: SeedableConfig>(
    mut commands: Commands,
    asset_server: Res<AssetServer>,
) {
    let handle = asset_server.load::<D>(D::asset_path());
    commands.insert_resource(DefaultsHandle::<D>(handle));
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Test config type generated by the `GameConfig` derive macro.
    #[derive(Resource, Debug, Clone, PartialEq, Default, crate::GameConfig)]
    #[game_config(
        defaults = "TestDefaults",
        path = "config/test.ron",
        ext = "test.ron"
    )]
    struct TestConfig {
        value: f32,
    }

    // ── seed_config tests ────────────────────────────────────────────

    #[cfg(feature = "progress")]
    mod seed_config_tests {
        use super::*;

        fn test_app() -> App {
            let mut app = App::new();
            app.add_plugins((MinimalPlugins, AssetPlugin::default()))
                .init_asset::<TestDefaults>()
                .add_systems(Update, seed_config::<TestDefaults>.map(drop));
            app
        }

        /// Without a `DefaultsHandle` resource, `seed_config` reports zero
        /// progress and does not insert the `Config` resource.
        #[test]
        fn returns_zero_progress_without_handle() {
            let mut app = test_app();
            app.update();
            assert!(
                app.world().get_resource::<TestConfig>().is_none(),
                "TestConfig should not exist when no DefaultsHandle is present"
            );
        }

        /// When `DefaultsHandle` exists but the asset is not yet loaded,
        /// `seed_config` reports zero progress.
        #[test]
        fn returns_zero_progress_when_asset_not_loaded() {
            let mut app = test_app();

            // Insert a handle pointing to a non-existent asset.
            let handle: Handle<TestDefaults> = Handle::default();
            app.world_mut()
                .insert_resource(DefaultsHandle(handle));

            app.update();

            assert!(
                app.world().get_resource::<TestConfig>().is_none(),
                "TestConfig should not exist when the asset is not loaded"
            );
        }

        /// When the defaults asset is loaded, `seed_config` inserts the
        /// corresponding `Config` resource and reports done progress.
        #[test]
        fn inserts_config_when_asset_loaded() {
            let mut app = test_app();

            let defaults = TestDefaults { value: 99.0 };
            let handle = {
                let mut assets =
                    app.world_mut().resource_mut::<Assets<TestDefaults>>();
                assets.add(defaults)
            };
            app.world_mut()
                .insert_resource(DefaultsHandle(handle));

            app.update();

            let config = app
                .world()
                .get_resource::<TestConfig>()
                .expect("TestConfig should be inserted after seed");
            assert!(
                (config.value - 99.0).abs() < f32::EPSILON,
                "TestConfig.value should be 99.0 from the loaded defaults, got {}",
                config.value
            );
        }

        /// After seeding once, running `seed_config` again does not re-insert
        /// the resource (idempotent). Reports done progress on subsequent ticks.
        #[test]
        fn seed_is_idempotent() {
            let mut app = test_app();

            let defaults = TestDefaults { value: 99.0 };
            let handle = {
                let mut assets =
                    app.world_mut().resource_mut::<Assets<TestDefaults>>();
                assets.add(defaults)
            };
            app.world_mut()
                .insert_resource(DefaultsHandle(handle));

            // First tick — seeds the config.
            app.update();

            // Mutate the config directly to detect re-insertion.
            app.world_mut()
                .resource_mut::<TestConfig>()
                .value = 1.0;

            // Second tick — should NOT re-insert (value stays at 1.0).
            app.update();

            let config = app.world().resource::<TestConfig>();
            assert!(
                (config.value - 1.0).abs() < f32::EPSILON,
                "seed_config should be idempotent — value should remain 1.0, got {}",
                config.value
            );
        }
    }

    // ── propagate_defaults tests ─────────────────────────────────────

    mod propagate_defaults_tests {
        use super::*;

        fn test_app() -> App {
            let mut app = App::new();
            app.add_plugins((MinimalPlugins, AssetPlugin::default()))
                .init_asset::<TestDefaults>()
                .init_resource::<TestConfig>()
                .add_systems(Update, propagate_defaults::<TestDefaults>);
            app
        }

        /// When only an `Added` event fires (no `Modified`), the config
        /// remains unchanged.
        #[test]
        fn config_unchanged_when_no_modified_event() {
            let mut app = test_app();

            let defaults = TestDefaults { value: 10.0 };
            let handle = {
                let mut assets =
                    app.world_mut().resource_mut::<Assets<TestDefaults>>();
                assets.add(defaults)
            };
            app.world_mut()
                .insert_resource(DefaultsHandle(handle));

            // Two updates: PostUpdate flushes Added, First rotates buffer.
            app.update();
            app.update();

            let config = app.world().resource::<TestConfig>();
            assert!(
                (config.value - 0.0).abs() < f32::EPSILON,
                "config should remain at default (0.0) when only Added fires, got {}",
                config.value
            );
        }

        /// When a `Modified` event fires after mutating the asset,
        /// `propagate_defaults` replaces the `Config` resource with new
        /// values.
        #[test]
        fn config_replaced_on_modified_event() {
            let mut app = test_app();

            let defaults = TestDefaults { value: 10.0 };
            let handle = {
                let mut assets =
                    app.world_mut().resource_mut::<Assets<TestDefaults>>();
                assets.add(defaults)
            };
            app.world_mut()
                .insert_resource(DefaultsHandle(handle.clone()));

            // Let Added event settle.
            app.update();
            app.update();

            // Trigger Modified by mutating the asset.
            {
                let mut assets =
                    app.world_mut().resource_mut::<Assets<TestDefaults>>();
                let asset = assets
                    .get_mut(handle.id())
                    .expect("asset should exist");
                asset.value = 77.0;
            }

            // PostUpdate flushes Modified, First rotates buffer, Update runs
            // system.
            app.update();
            app.update();

            let config = app.world().resource::<TestConfig>();
            assert!(
                (config.value - 77.0).abs() < f32::EPSILON,
                "TestConfig.value should be 77.0 after Modified event, got {}",
                config.value
            );
        }
    }

    // ── init_defaults_handle tests ───────────────────────────────────

    mod init_defaults_handle_tests {
        use super::*;

        /// After the startup system runs, `DefaultsHandle<TestDefaults>`
        /// should exist as a resource.
        #[test]
        fn inserts_defaults_handle_on_startup() {
            let mut app = App::new();
            app.add_plugins((MinimalPlugins, AssetPlugin::default()))
                .init_asset::<TestDefaults>()
                .add_systems(Startup, init_defaults_handle::<TestDefaults>);

            app.update();

            assert!(
                app.world()
                    .get_resource::<DefaultsHandle<TestDefaults>>()
                    .is_some(),
                "DefaultsHandle<TestDefaults> should exist after startup"
            );
        }
    }
}
